### ISSUE TITLE
Imports of the same package is not combined

### ISSUE THREAD

**Issue by Zhuvikin** [lydell/eslint-plugin-simple-import-sort#1]
Imports of the same package are to be combined to the one import.

---

**Steps to reproduce:**

Try to fix the following
```
import React from 'react'
import { Component } from 'react'
```

**Actual result:**
```
import React from 'react'
import { Component } from 'react'
```

**Expected result:**
```
import React, { Component } from 'react'
```

---

**Steps to reproduce:**

Try to fix the following
```
import './styles.scss'
import './styles.scss'
```

**Actual result:**
```
import './styles.scss'
import './styles.scss'
```

**Expected result:**
```
import './styles.scss'
```

**Comment by lydell** [comment]
Hi! Thanks for the issue!

I thought about this too a while ago, but I came to the conclusion that it is better to use [import/no-duplicates](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-duplicates.md). It does not support autofix, but I don’t see why that couldn’t be added to it.

What do you think?

**Comment by lydell** [comment]
Autofix PR for no-duplicates: https://github.com/benmosher/eslint-plugin-import/pull/1312
