### ISSUE TITLE
ESLint: Definition for rule 'simple-import-sort/exports' was not found.(simple-import-sort/exports)

### ISSUE THREAD

**Issue by LastStranger** [lydell/eslint-plugin-simple-import-sort#101]
<img width="715" alt="截屏2022-04-06 下午1 04 42" src="https://user-images.githubusercontent.com/29811304/161899573-1060bdde-6bf3-4b52-a863-0cadd6002b50.png">
any possible reason?

**Comment by lydell** [comment]
Hi!

- Maybe you installed an old version of the plugin? simple-import-sort/imports and simple-import-sort-/exports are only available in [version 6](https://github.com/lydell/eslint-plugin-simple-import-sort/blob/main/CHANGELOG.md#version-600-2020-11-15) or later.
- Maybe you forgot to run `npm install`, so ESLint can’t find the package at all?
- Maybe you installed ESLint and the plugin _globally?_ According to ESLint’s documentation, configs and plugins _have_ to be installed _locally._ Do other plugins work for you?

**Comment by lydell** [comment]
Closing because no response.
