### ISSUE TITLE
Definition for rule 'simple-import-sort/sort' was not found.(simple-import-sort/sort)

### ISSUE THREAD

**Issue by AntonGG** [lydell/eslint-plugin-simple-import-sort#102]
Hello, can you help me?
i want css imports to be inserted at the end
<img width="806" alt="image" src="https://user-images.githubusercontent.com/16887654/162631672-95f9671d-fe7c-49ac-bcc7-a8ba0abc4541.png">
<img width="717" alt="image" src="https://user-images.githubusercontent.com/16887654/162631690-b6b4d408-ffe7-4b72-9fb5-978cba3bf47c.png">

**Comment by lydell** [comment]
Hi! `simple-import-sort/sort` was renamed to `simple-import-sort/imports` in version 6:

https://github.com/lydell/eslint-plugin-simple-import-sort/blob/main/CHANGELOG.md#version-600-2020-11-15

**Comment by lydell** [comment]
Closing because no response.
