### ISSUE TITLE
Sorting unassigned import does not work

### ISSUE THREAD

**Issue by ilyub** [lydell/eslint-plugin-simple-import-sort#104]
Thx for the plugin.
It looks like "imports" rule does not sort unassigned import:
```ts
import "./second";
import "./first";
```
With assigned import it works fine.

**Comment by lydell** [comment]
Hi!

As mentioned in https://github.com/lydell/eslint-plugin-simple-import-sort#not-for-everyone and https://github.com/lydell/eslint-plugin-simple-import-sort#is-sorting-importsexports-safe, those are considered “side effect” imports and they always stay in the original order for safety. That isn’t and will not be configurable.

**Comment by ilyub** [comment]
Thx for the explanation.
For anyone who still wants to sort unassigned import, I found that "import/order" has "warnOnUnassignedImports".
