### ISSUE TITLE
Prettier integration

### ISSUE THREAD

**Issue by TutoDS** [lydell/eslint-plugin-simple-import-sort#105]
Hi
How to integrate with Prettier?
I'm trying use this plugin with Prettier, already set my VSCode to format and fix ESLint on save, but the imports not sort.

Anyway to do a automatically sort with prettier on format?

**Comment by lydell** [comment]
Hi! This is an ESLint plugin, so you can’t run it through Prettier or something like that.

What I do is having Prettier run on save in VSCode, as well as ESLint fix. And it works pretty well! Sometimes I have to save twice.

Having import sorting in Prettier would be the dream. I’m keeping an eye on https://github.com/trivago/prettier-plugin-sort-imports for that reason.

I have this in my VSCode settings.json in case it helps:

```json
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
        "source.fixAll.eslint": true
    },
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[typescript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    // etc
```

**Comment by lydell** [comment]
Closing because no response.

**Comment by helloint** [comment]
I love the plugin, but I think there maybe some confusion in the readme:
```
recommend using [Prettier](https://prettier.io/)
```
actually it can't affect with prettier cli

**Comment by lydell** [comment]
@helloint What do you mean?

**Comment by helloint** [comment]
@lydell I'm using Prettier with ESLint, my IDE is Intellij IDEA. I have configured husky to do prettier format when commit. When coding, I will let Intellij to do Prettier format (Right menu, 'Reformat with Prettier') from time to time, to resolve the error hint.
<img width="257" alt="image" src="https://user-images.githubusercontent.com/4143533/199980937-207dda90-b684-40e0-815c-10c725538c0a.png">
When I saw the message 'recommend using Prettier' in readme, I thought the plugin can work with Prettier, means just use Prettier to do format, and it will take affect. But not, I have to click 'Fix ESLint Problems'.
I want to know why Prettier doesn't work, then I saw this ticket and I understand it is because the plugin is a ESLint plugin.

No offense, just, I hope Prettier can handle all code format/style issues.

**Comment by StepanMynarik** [comment]
> Hi! This is an ESLint plugin, so you can’t run it through Prettier or something like that.
> 
> What I do is having Prettier run on save in VSCode, as well as ESLint fix. And it works pretty well! Sometimes I have to save twice.
> 
> Having import sorting in Prettier would be the dream. I’m keeping an eye on https://github.com/trivago/prettier-plugin-sort-imports for that reason.
> 
> I have this in my VSCode settings.json in case it helps:
> 
> ```json
>     "editor.formatOnSave": true,
>     "editor.codeActionsOnSave": {
>         "source.fixAll.eslint": true
>     },
>     "[javascript]": {
>         "editor.defaultFormatter": "esbenp.prettier-vscode"
>     },
>     "[typescript]": {
>         "editor.defaultFormatter": "esbenp.prettier-vscode"
>     },
>     // etc
> ```

It is already out, why are you keeping an eye on it?
I would love to know what is so appealing on it when your plugins works perfect and has zero open issues?

**Comment by helloint** [comment]
I also noticed that prettier sort plugins, but it looks like we need to keep 2 duplicated configures for each of them?

**Comment by lydell** [comment]
@StepanMynarik To get rid of red squiggly underlines in my editor.

@helloint You use one or the other, not both.

**Comment by StepanMynarik** [comment]
> @StepanMynarik To get rid of red squiggly underlines in my editor.

Thank you for the quick response. I do not understand however :D
I wanted to know what are the benefits of trivago ```prettier``` based solution over yours?
What editor errors do you mean? I don't see any.
You think trivago solution should replace yours over time?

Please give me specific answers brother <3

**Comment by lydell** [comment]
I use ESLint plugins in all text editors I use (for example VSCode). They underline code with ESLint errors with red (or yellow) squiggly lines. That’s annoying for the imports.
