### ISSUE TITLE
Plugin removed spaces after the comma while running autofix

### ISSUE THREAD

**Issue by ansidev** [lydell/eslint-plugin-simple-import-sort#108]
## Reproduce steps
1. Clone the repository: https://github.com/ansidev/nextjs-starter
2. Switch to the branch `issue/eslint-plugin-simple-import-sort-issue`.
3. Run `yarn install`.
4. Open the file `pages/api/hello.ts`, the second line is

```js
import type { NextApiResponse, NextApiRequest } from 'next'
```

6. Run `yarn lint --fix`.

## Actual behavior

The error was fixed but the above line was changed to

```js
import type { NextApiRequest,NextApiResponse } from 'next'
```

## Expected behavior

```js
import type { NextApiRequest, NextApiResponse } from 'next'
```

(There is a space after the comma).

**Comment by lydell** [comment]
Hi! Have you read this? https://github.com/lydell/eslint-plugin-simple-import-sort#the-sorting-autofix-causes-some-odd-whitespace

**Comment by ansidev** [comment]
> Hi! Have you read this? [lydell/eslint-plugin-simple-import-sort#the-sorting-autofix-causes-some-odd-whitespace](https://github.com/lydell/eslint-plugin-simple-import-sort#the-sorting-autofix-causes-some-odd-whitespace)

@lydell Thank you, I got it, and now it worked perfectly.
