### ISSUE TITLE
Please allow for grouping parent imports apart from sibling imports.

### ISSUE THREAD

**Issue by Asday** [lydell/eslint-plugin-simple-import-sort#11]
```es6
import { something } from '../otherModule/something'
import { somethingElse } from './somethingElse'
```

Becomes:

```es6
import { something } from '../otherModule/something'

import { somethingElse } from './somethingElse'
```

**Comment by lydell** [comment]
Hi! I've thought about this issue a lot, and decided that keeping all relative imports in one group and sorting them alphabetically is such a simple rule that gives really good results in 90% of cases that I'm going to stay with that. Thanks for the suggestion, though!

**Comment by lydell** [comment]
This is now possible in v5.0.0 using
[custom grouping](https://github.com/lydell/eslint-plugin-simple-import-sort/tree/d1d59be47b08733990a8a62f7caf735cdad420f9#custom-grouping).

For example:

```json
{
  "rules": {
    "simple-import-sort/sort": [
      "error",
      {
        "groups": [["^\\u0000"], ["^@?\\w"], ["^[^.]"], ["^\\.\\."], ["^\\."]]
      }
    ]
  }
}
```
