### ISSUE TITLE
Grouping exports

### ISSUE THREAD

**Issue by raymondwang** [lydell/eslint-plugin-simple-import-sort#130]
Hey! Love the package. I'm wondering if you'd be interested in adding support for grouping exports. Most of the time this probably isn't valuable, but we sometimes use internal packages or directories as entry points for (often heavy) external package dependencies. For example:

```ts
// /packages/my-external-component-wrapper/index.ts

export { ExternalComponent } from '@external/component';

export { myHelperFunctionForWorkingWithExternalComponent } from './foo/bar';
```

Keeping this grouping separate seems like it would be somewhat valuable in these cases. Is that something you'd be ideologically disinterested in?

**Comment by lydell** [comment]
Hi!

You can group exports by adding comments.

https://github.com/lydell/eslint-plugin-simple-import-sort#exports

> Sequences of re-exports (exports with `from`) are sorted. Other types of exports are not reordered.
>
> Unlike imports, there’s no automatic grouping of exports. Instead a comment on its own line starts a group. This leaves the grouping up to you to do manually.

**Comment by lydell** [comment]
Either way, adding support for sorting exports took a lot of work:

- https://github.com/lydell/eslint-plugin-simple-import-sort/issues/21
- https://github.com/lydell/eslint-plugin-simple-import-sort/pull/53
- https://github.com/lydell/eslint-plugin-simple-import-sort/pull/53
- https://github.com/lydell/eslint-plugin-simple-import-sort/pull/55

I’m happy with what we ended up with and I’m not open for changing that.

**Comment by raymondwang** [comment]
Fair enough, thanks for the reply. Comments are sort of an awkward solution because it's a pattern we use a lot, and I'm not certain there's a whole lot of value in using comments just to group exports if it won't be consistently applied. Appreciate it!
