### ISSUE TITLE
Sorting by line length

### ISSUE THREAD

**Issue by jz222** [lydell/eslint-plugin-simple-import-sort#132]
Thanks for your work. Is it possible sort the import statements within a group by their total line length instead of alphabetically?

**Comment by lydell** [comment]
Hi! No, that’s not possible and it’s not something I’m willing to add.

**Comment by azat-io** [comment]
You can use eslint-plugin-perfectionist. It can sort the imports by line length:

https://github.com/azat-io/eslint-plugin-perfectionist
