### ISSUE TITLE
So how do you remove blank lines between groups?

### ISSUE THREAD

**Issue by Mitsunee** [lydell/eslint-plugin-simple-import-sort#134]
The README mentions "Remove blank lines between groups." as a thing you can do with custom grouping, but never mentions how to actually do it. I do not like these empty lines and would like to disable them (i.e. join on only one newline character)

**Comment by lydell** [comment]
It does mention it, it’s just very subtle:

> The inner arrays are joined with one newline; the outer arrays are joined with two (creating a blank line).

A bit further down, there’s also a link to examples, which contains:

https://github.com/lydell/eslint-plugin-simple-import-sort/blob/d94fbd968eefc6ba8c225c81982094b4d1831aa2/examples/.eslintrc.js#L99-L122

**Comment by Mitsunee** [comment]
I understood "Remove blank lines between groups." to mean that there is a way to configure whether groups are joined on one or two newlines. Is there no way to do that other than having all patterns in the same group? If so the sentence I quoted is a bit missleading since it implies the use of multiple groups.

**Comment by lydell** [comment]
> Is there no way to do that other than having all patterns in the same group?

Correct.

> If so the sentence I quoted is a bit missleading since it implies the use of multiple groups.

What could a less misleading sentence look like?

**Comment by Mitsunee** [comment]
> What could a less misleading sentence look like?

How about "Avoid blank lines between imports by using a single group."?
