### ISSUE TITLE
How can I make imports with a capitalized first letter always come first?

### ISSUE THREAD

**Issue by so1ve** [lydell/eslint-plugin-simple-import-sort#135]
Like:

```ts
import { UndefinedTheme, colors } from "./colors";
```

Is sorted to
```ts
import { colors,UndefinedTheme } from "./colors";
```

**Comment by lydell** [comment]
Hi! That is not possible, and I’m not interested in making it possible.

I haven’t tested it, but there’s a chance that you can use https://eslint-plugin-perfectionist.azat.io/rules/sort-named-imports instead, with the `alphabetical` sorting.

**Comment by so1ve** [comment]
Thanks~!
