### ISSUE TITLE
Question: how to approach the workaround for padding-line-between-statements?

### ISSUE THREAD

**Issue by mfxart** [lydell/eslint-plugin-simple-import-sort#137]
### how do I do it?

The docs says: 
> Since blank lines are removed, you might get slight incompatibilities with the [lines-around-comment](https://eslint.org/docs/rules/lines-around-comment) and [padding-line-between-statements](https://eslint.org/docs/rules/padding-line-between-statements) rules – I don’t use those myself, but **I think there should be workarounds.**

I tried different variations of the workaround, but with no luck. 

my eslint config:
```JSON
 "padding-line-between-statements": [
      "error",
      {
        "blankLine": "always",
        "prev": ["case", "default"],
        "next": "*"
      },
      {
        "blankLine": "always", // <==== force blankLine between imports
        "prev": ["import"],
        "next": ["import"]
      }
    ],
 "import-newlines/enforce": [
      "error",
      {
        "items": 1,
        "semi": true,
        "forceSingleLine": false
      }
    ],
    "import/no-duplicates": "error",
    "import/first": "error",
    "sort-imports": "off",
    "simple-import-sort/imports": [
      "error",
      {
        "groups": [
          ["^react$"],
          ["^(?!(enums|config|hooks|components|ui))", "^@"],
          ["@mypkg/shared"],
          ["^@mypkg/.*"], // <====== does not work with padding-line-between-statements

// ========= workaround for my selected packages:
          ["^enums.*"],
          ["^config.*"],
          ["^hooks.*"],
          ["^components.*"],
// ========= end of workaround for my packages:

          ["^ui.*"], , // <====== does not work with padding-line-between-statements
          [
            "^\\.\\.(?!/?$)",
            "^\\.\\./?$",
            "^\\./(?=.*/)(?!/?$)",
            "^\\.(?!/?$)",
            "^\\./?$",
            "^\\u0000"
          ]
        ]
      }
    ],
    "import/newline-after-import": ["error", { "count": 2 }]
  },
  "settings": {
    "import/internal-regex": "^@mypkg/",
    "import/resolver": {
      "node": {
        "paths": ["app", "packages"],
        "extensions": [".js", ".jsx", ".ts", ".tsx"]
      }
    }
  }
  ```
  
  problem:
  I need to have a new line between each import statement.
  
  this is  ✅ OK and matches padding-line-between-statements, as groups specified in new arrays:
 ```JavaScript
 import {
  MyEnum
} from 'enums';

import {
  MyConfig,
} from 'config';

import {
 useMyHook
} from 'hooks';
```

this is ❌  NOT OK and conflicts with the padding-line-between-statements (no newline between the groups):
```JavaScript
import {
  MyUiImport
} from 'ui/components';
import {
  MyAnotherUiImport
} from 'ui/myFeature/nested/components';
```
or

```JavaScript
import {
  MyUiImport
} from '@mypkg/my-pkg1';
import {
  MyAnotherUiImport
} from '@mypkg/my-pkg2;
```

could you help me with creating a workaround for the import sort grouping new line removal?

**Comment by lydell** [comment]
Hi!

I wrote that 5 years ago and don’t remember exactly what I was thinking anymore, but I would imagine the workaround includes configuring the `padding-line-between-statements` ESLint rule to _not_ enforce stuff about `import` statements, since that’s simply not supported by this plugin. If empty lines between each import is a must, you either need to find a different plugin or fork this one.

**Comment by lydell** [comment]
Closing because no response.
