### ISSUE TITLE
Please update your docs

### ISSUE THREAD

**Issue by vtarelkin** [lydell/eslint-plugin-simple-import-sort#138]
I'm new into prettier and eslint and I've got this "use autofix" message. I've read documentation twice, but there is no clear way how to run this autofix. I thought that it is perfomed on the fly!

After reading other manuals I finally got that I have to run in terminal

npm run lint:fix
> @ lint:fix /home/runner/eslint-sort-imports
> npm run lint -- --fix

> @ lint /home/runner/eslint-sort-imports
> eslint . "--fix"

It should be clear from your docs, shouldn't it?

**Comment by mfxart** [comment]
when using vscode you could set fixOnSave in settings.json to true, like:

  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },

**Comment by lydell** [comment]
Explaining how `npm run` works is out of scope for this readme, but I added links to `eslint --fix` in more places in the readme.
