### ISSUE TITLE
Using without new lines between groups

### ISSUE THREAD

**Issue by avin-kavish** [lydell/eslint-plugin-simple-import-sort#140]
Any way to use this without adding new lines between groups?

**Comment by lydell** [comment]
Duplicate of https://github.com/lydell/eslint-plugin-simple-import-sort/issues/134

In that issue we improved the readme to make it easier to find/understand. Do you have any ideas on how to further improve it?

**Comment by avin-kavish** [comment]
Yeah, few things.
 
 First I clicked on [this]( https://github.com/lydell/eslint-plugin-simple-import-sort/blob/d94fbd968eefc6ba8c225c81982094b4d1831aa2/examples/groups.no-blank-lines.js) hoping to find the config for it there, I didn't realise all the configs were in one file and example code was in separate file. Maybe group the relevant config and code example together in folders?

It's not clear by this sentence, `Avoid blank lines between imports by using a single group`, that "single group" means to use a single nested array instead of many nested arrays. So I think it should be explained from the beginning.
 
So something like, config uses a nested array of strings. The outer array groups declarations and separates them by a blank/new line. Inner arrays order declarations within the outer group.


Also you can add a FAQ section with an example.

## FAQ

### How to remove blank line between groups?

Change config to ....

Read more above.
