### ISSUE TITLE
sorted import specifiers missing space

### ISSUE THREAD

**Issue by lovetingyuan** [lydell/eslint-plugin-simple-import-sort#146]
origin: `import { ref, computed, watchEffect, shallowRef } from 'vue'`
after fix: `import { computed, ref, shallowRef,watchEffect } from 'vue'`,
notice that there should be a space between "shallowRef" and "watchEffect", but in fact the space is missing.

here is an example : https://stackblitz.com/edit/stackblitz-starters-wjlmw9?file=index.js
you can run `npm run lint` to verify the issue. Thanks.

**Comment by lydell** [comment]
Hi! See https://github.com/lydell/eslint-plugin-simple-import-sort#the-sorting-autofix-causes-some-odd-whitespace

**Comment by lovetingyuan** [comment]
ok, thank you, I got it.
