### ISSUE TITLE
 I thought library imports were supposed to come before relative imports?

### ISSUE THREAD

**Issue by ryancwalsh** [lydell/eslint-plugin-simple-import-sort#150]
My project extends 'canonical/auto' (from `eslint-config-canonical`), which has `eslint-plugin-simple-import-sort` as a dependency.

I love the idea.

Why is it auto-fixing this?

```ts
import { PrismaClient } from '@prisma/client';

import { NODE_ENV } from '../constants/config';
```

I thought library imports were supposed to come before relative imports?

I am surprised that your rule is swapping them (and removing the empty line) to be:

```ts
import { NODE_ENV } from '../constants/config';
import { PrismaClient } from '@prisma/client';
```

I'm having a hard time understanding https://github.com/lydell/eslint-plugin-simple-import-sort#custom-grouping

I definitely want relative imports to be the last group.

Thanks!

**Comment by lydell** [comment]
eslint-config-canonical has configured this plugin to only have one single group of imports, where all the imports are sorted alphabetically: https://github.com/gajus/eslint-config-canonical/blob/b6320206a5c6cc7247ca575584178b874be0abd4/configurations/eslintrc.js#L691

I they had used the defaults of this plugin, your imports would have been sorted like you expect.

**Comment by ryancwalsh** [comment]
Wow, thank you for your fast and helpful answer!

I wouldn't have expected them to override the defaults like that.

Now that I've set it to:

```
    'simple-import-sort/imports': [
      'error',
      {
        groups: [
          // Side effect imports.
          ['^\\u0000'],
          // Node.js builtins prefixed with `node:`.
          ['^node:'],
          // Packages.
          // Things that start with a letter (or digit or underscore), or `@` followed by a letter.
          ['^@?\\w'],
          // Absolute imports and other imports such as Vue-style `@/foo`.
          // Anything not matched in another group.
          ['^'],
          // Relative imports.
          // Anything that starts with a dot.
          ['^\\.'],
        ],
      },
    ],
```

the file I originally asked about is fixed.

But why does it sort these this way (in a different file)?

```ts
import '../styles/globals.scss';
// Core styles are required for all packages:
import '@mantine/core/styles.css';

import { ClerkProvider } from '@clerk/nextjs';
import { ColorSchemeScript, createTheme, MantineProvider } from '@mantine/core';
import { type Metadata } from 'next';
import { Inter } from 'next/font/google';
import Head from 'next/head';
```

If I want the first 2 imports (CSS) to be in a chunk at the bottom, what should I change?

Thanks!

**Comment by lydell** [comment]
`import '../styles/globals.scss';` is matched by the first group – side effect imports.

`import '@mantine/core/styles.css';` is matched by the group that mentions `@`.

You could add a group for `"\\.s?css$"` – files ending with .css or .scss.

**Comment by ryancwalsh** [comment]
Amazing! Thank you so much for all of your help!
