### ISSUE TITLE
Error: Run autofix to sort these imports!

### ISSUE THREAD

**Issue by dmurdasova** [lydell/eslint-plugin-simple-import-sort#151]
Hello!

Thank you for your job and such a great plugin!

I have a pretty simple config .eslintrc.json:

```javascript
{
  "root": true,
  "ignorePatterns": [
    "**/*"
  ],
  "plugins": [
    "@nx",
    "simple-import-sort"
  ],
  "rules": {
    "simple-import-sort/imports": "error"
  }
}
```
When I run eslint with --fix flag, imports are sorted, but I still see an error as the linted result.

The example of unsorted imports:
```javascript
import { isIconString } from './isIconString';
import classNames from 'classnames';
import isEmpty from 'lodash/isEmpty';
import Icon from '../components/Icon';
import React from 'react';
```
The result of the "eslint --fix" command:
```javascript
import classNames from 'classnames';
import isEmpty from 'lodash/isEmpty';
import React from 'react';
import Icon from '../components/Icon';
import { isIconString } from './isIconString';
```

So, everything is sorted, but I have the next output for each file that contains imports:

```javascrtipt
  1:1   error    Run autofix to sort these imports!        simple-import-sort/imports

✖ 77 problems (66 errors, 11 warnings)
  66 errors and 0 warnings potentially fixable with the `--fix` option.
```
![Screenshot 2023-11-23 at 11 34 39](https://github.com/lydell/eslint-plugin-simple-import-sort/assets/127208315/cc181faa-4956-4b85-b749-5370819e6652)

What could be wrong?
I use typescript of version ~5.1.3.

Thanks!

**Comment by lydell** [comment]
Hi! Can you provide steps to reproduce? Probably, the easiest thing is if you create a minimal reproduction repo that I can clone and run `npm ci && npm test` to reproduce.

**Comment by dmurdasova** [comment]
Sure, there is a repo: https://github.com/dmurdasova/imports-error/tree/main

Please, pay attention, that I use **pnpm** instead of **npm** (not sure if it is important) and **nx**.

Before installing dependencies you need to run the "preinstall" script.
Then, install deps both in the root directory, and "libs/test" directory.

When you call the "lint" or the "lint:fix" script, you will get the same error: ![Screenshot 2023-11-23 at 13 45 15](https://github.com/lydell/eslint-plugin-simple-import-sort/assets/127208315/b9ddfe70-5e29-4fe6-85ac-fab1ecea934b)

**Comment by lydell** [comment]
Thanks! Can you reduce the repo down? Often when I report issues myself, I find the actual problem while doing so. It would be nice to get rid of nx, and as many unnecessary files as possible. If it still happens in a more minimal repo, I can take a look.

**Comment by dmurdasova** [comment]
Did it, removed nx and other extra packages. But I still have this issue :(

**Comment by dmurdasova** [comment]
Node and pnpm versions:

![Screenshot 2023-11-23 at 16 50 40](https://github.com/lydell/eslint-plugin-simple-import-sort/assets/127208315/e0e65ce0-c1bf-4be2-b417-74c572e71881)

**Comment by lydell** [comment]
Awesome! I cloned your repo, but wasn’t able to reproduce your problem:

```
~/stuff/imports-error main                                                                                                                                                                                                           20.5.0
❯ npm run lint

> @test@0.1.0 lint
> eslint "./**/*.{js,jsx,ts,tsx}"


/Users/simon/stuff/imports-error/libs/test/src/components/Block/Block.tsx
  1:1  error  Run autofix to sort these imports!  simple-import-sort/imports

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.


~/stuff/imports-error main                                                                                                                                                                                                           20.5.0
❯ npm run lint:fix

> @test@0.1.0 lint:fix
> eslint --fix "./**/*.{js,jsx,ts,tsx}"


~/stuff/imports-error main !1                                                                                                                                                                                                        20.5.0
❯ npm run lint

> @test@0.1.0 lint
> eslint "./**/*.{js,jsx,ts,tsx}"


~/stuff/imports-error main !1                                                                                                                                                                                                        20.5.0
❯ git diff
diff --git a/libs/test/src/components/Block/Block.tsx b/libs/test/src/components/Block/Block.tsx
index a4c69c6..1985a11 100644
--- a/libs/test/src/components/Block/Block.tsx
+++ b/libs/test/src/components/Block/Block.tsx
@@ -1,5 +1,6 @@
 import isEmpty from 'lodash/isEmpty';
 import React from 'react';
+
 import { Icon } from '../Icon';
 import { isValid } from './isValid';
```

**Comment by dmurdasova** [comment]
Interesting! I'll try to get why I get errors.
Thank you for your time! :)

**Comment by kaidjohnson** [comment]
@dmurdasova Did you end up finding a solution to this issue? We're seeing the same problem (also using `pnpm` and not `npm`):

```
 $ node --version
v20.9.0
```

```
 $ pnpm --version
9.6.0
```

It doesn't look like the repo for reproducing the issue exists any more, so I can't test-drive it there and it looks like @lydell was using `npm` when trying to reproduce. I think this issue is still valid for `pnpm` users.
