### ISSUE TITLE
Duplicate imports are not being removed

### ISSUE THREAD

**Issue by RoySchiffmannGrip** [lydell/eslint-plugin-simple-import-sort#152]
For some reason when I'm having duplicated import from the same module, auto-fix unifies them into the same import line but unfortunately it keeps the duplication, for example:
```
import { something } from "./somewhere.ts";
import { something } from "./somewhere.ts";
```

after auto-fix will turn to be:
```
import { something, something } from "./somewhere.ts";
```

Is there already a configuration that will auto-delete the redundant duplicated imports?

**Comment by lydell** [comment]
Hi! This plugin does not handle removing duplicates, only sorting. (This is hinted at slightly at https://github.com/lydell/eslint-plugin-simple-import-sort#example-configuration, which suggests using [import/no-duplicates](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-duplicates.md).)
