### ISSUE TITLE
Conflict between eslint-plugin-simple-import-sort and esbenp.prettier-vscode

### ISSUE THREAD

**Issue by giovannetti-eric** [lydell/eslint-plugin-simple-import-sort#153]
I'm using for years this VSCode plugin for Prettier code formatting [Prettier - Code formatter](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) coupled with formatting on save.

This was working fine with eslint-plugin-simple-import-sort, but since few months, there is conflict between them.

For example, when I save I get generated by esbenp.prettier-vscode:
`import { RouteSlug, getRoute } from "@/app/_libs/routing/getRoute";`

But eslint-plugin-simple-import-sort report an error because it want to have:
`import { getRoute, RouteSlug } from "@/app/_libs/routing/getRoute";`

I wonder if it's a eslint-plugin-simple-import-sort or esbenp.prettier-vscode change that is causing this recent order change.

**Comment by lydell** [comment]
Hi!

esbenp.prettier-vscode uses Prettier. It ships with a built-in distribution of Prettier (as far as I remember). Prettier does not sort imports. So generally they work well together.

If you have Prettier installed in your project, esbenp.prettier-vscode uses that instead.

There are also Prettier plugins that you can install in your project. There are a few plugins for sorting imports within Prettier. My guess is that you have such a plugin.

**Comment by giovannetti-eric** [comment]
Ok, I finally found the source of my problem, it's the commented line in VSCode config:

```
"editor.codeActionsOnSave": {
    "source.fixAll": "explicit",
    // "source.organizeImports": "explicit"
},
```

This feature didn't sort in the same order the import properties, causing this problem.
