### ISSUE TITLE
Only import grouping, not alphabetical sorting

### ISSUE THREAD

**Issue by kluplau** [lydell/eslint-plugin-simple-import-sort#16]
I would love to have an option to disable alphabetical sorting. I just want import grouping.

Is that possible any way? Can't seem to find a solution.

**Comment by lydell** [comment]
Why don’t you want sorting?

**Comment by kluplau** [comment]
My peer programmers are struggling with learning the stack, and I'm trying to introduce the lowest level of pain regarding linting, etc. 

I does matter that imports are grouped, but it doesn't matter if it's alphabetical sorted.

**Comment by lydell** [comment]
How does sorting introduce more pain than grouping?

**Comment by kluplau** [comment]
Two rules is twice as much pain as one. 

We need logical order more than alphabetical orde.

**Comment by lydell** [comment]
This plugin provides a single ESLint rule. It says "Run autofix to sort these imports!" once per file that contains unsorted imports, basically. I don’t see how saying "Run autofix to group these imports!" would be any different.

**Comment by kluplau** [comment]
Technically it's a single rule - but practically it's two: Sorting and grouping. We only need the latter. 

What's up with the tone of your replies? I just have another use-case than you, it's not a personal attack.

**Comment by lydell** [comment]
Sorry! It’s really hard to get tone across in text form on the Internet. I should have added emojis and some extra words here and there to show that I’m actually genuinely curious about your use case! I just want to make sure that I completely understand what you need and why before doing anything else, because I really want to keep this plugin free of options if possible.

**Comment by kluplau** [comment]
No worries. 
Yeah I follow — simplicity is key. Guess I have to find an alternative, create my own, or deal with the sorting.
Thank you for taking your time to answer my feature request.

**Comment by lydell** [comment]
I think forking this repo and removing all sorting stuff wouldn't be too much work.

**Comment by dima-f1** [comment]
> No worries.
> Yeah I follow — simplicity is key. Guess I have to find an alternative, create my own, or deal with the sorting.
> Thank you for taking your time to answer my feature request.

@kluplau Did you find any alternative?
