### ISSUE TITLE
Add `recommended` preset?

### ISSUE THREAD

**Issue by fisker** [lydell/eslint-plugin-simple-import-sort#168]
Instead of 

```js
import simpleImportSort from "eslint-plugin-simple-import-sort";

export default [
  {
    plugins: {
      "simple-import-sort": simpleImportSort,
    },
    rules: {
      "simple-import-sort/imports": "error",
      "simple-import-sort/exports": "error",
    },
  },
];
```

We can use

```js
import simpleImportSort from "eslint-plugin-simple-import-sort";

export default [
  simpleImportSort.configs.recommended,
];
```

**Comment by lydell** [comment]
Hi!

Previous discussions (a bit outdated, this one is the first one for flat config): #66, #14, #142

Personally I don’t like it. It removes just a couple of lines, with the cost of if you want to change any options it’s harder. And I need to put describe what `recommended` does in the readme anyway.

**Comment by fisker** [comment]
Thanks!

**Comment by thernstig** [comment]
@lydell is this something you can reconsider? Most ESLint flat config plugins do export a `config` property nowadays. Example:

```js
export default defineConfig([
  js.configs.recommended,
  stylistic.configs.recommended,
  eslintPluginUnicorn.configs.recommended,
  reactPlugin.configs.flat.recommended,
  reactPlugin.configs.flat['jsx-runtime'],
  reactHooks.configs['recommended-latest'],
  jsdoc.configs['flat/recommended-typescript'],
  tseslintConfigs.strictTypeChecked,
  tseslintConfigs.stylisticTypeChecked,
]);
```

To me this has now become the opposite of what I think most people do, meaning using this plugin looks "more bloated" than other plugins. And it is so common to do this now that I think it becomes natural in a sense that you do not need a very elaborate explanation for it.

So I think this should be considered again:

```ts
import simpleImportSort from 'eslint-plugin-simple-import-sort';

export default defineConfig([
  simpleImportSort.configs.recommended,
]);
```
