### ISSUE TITLE
Doesnt sort typescript exports

### ISSUE THREAD

**Issue by AuthorProxy** [lydell/eslint-plugin-simple-import-sort#169]
doesnt sort this code blocks:
```

export enum model {
}

export enum anotherModel {
}
```

**Comment by lydell** [comment]
Hi! This is intentional

> Sequences of re-exports (exports with `from`) are sorted. Other types of exports are not reordered.

https://github.com/lydell/eslint-plugin-simple-import-sort?tab=readme-ov-file#exports
