### ISSUE TITLE
Add `meta.docs.description` to rule?

### ISSUE THREAD

**Issue by fisker** [lydell/eslint-plugin-simple-import-sort#171]
I guess the rule name is already enough to explain what it does, but when generating docs, it feels odd that other rules have descriptions, but our two rules don't, should we consider adding something there?

![image](https://github.com/lydell/eslint-plugin-simple-import-sort/assets/172584/f37788e2-1013-4e1b-8a60-76e18b19894a)

**Comment by lydell** [comment]
Sounds good!

Suggestion:

exports: "Automatically sort exports"
imports: "Automatically sort imports"

Do you want to make a PR?

**Comment by fisker** [comment]
Sure!
