### ISSUE TITLE
Imports not being sorted alphabetically w.r.t their group

### ISSUE THREAD

**Issue by tejas-1206** [lydell/eslint-plugin-simple-import-sort#184]
Hi, I've setup my project with this amazing plugin and it works great. But I came across something last night that has started creeping into my dreams as well.

My ESLint config:
The project is quite old and is currently being refactored and migrated, hence a bit complex grouping of imports.
I'm new to regex with very basic understanding of them. So, some regex rules were copied from the [examples](https://github.com/lydell/eslint-plugin-simple-import-sort/blob/main/examples/.eslintrc.js) shared in this repo. Others were added to achieve that grouping I wanted.

```js
import simpleImportSort from 'eslint-plugin-simple-import-sort';

export default [
  {
    plugins: {
      'simple-import-sort': simpleImportSort
    },
    rules: {
      'simple-import-sort/imports': [
        'error',
        {
          groups: [
            // Packages. `react` related packages come first.
            ['^react', 'react-dom', '^@?\\w+(?=react)'],
            // CSS/SCSS imports
            ['^.+\\.s?css$'],
            // Other external packages
            ['^@?\\w'],
            // Components
            ['antd', '^..*/common/', '^..*/components/'],
            // API handlers, models, and services
            ['useAxiosApiHandler', '^..*/api/'],
            // Parent imports. Put `..` last.
            ['^\\.\\.(?!/?$)', '^\\.\\./?$'],
            // Other relative imports. Put same-folder imports and `.` last.
            ['^\\./(?=.*/)(?!/?$)', '^\\.(?!/?$)', '^\\./?$'],
            // Utils and constants
            ['^.*/(constant|constants|utils)$']
          ]
        }
      ],
      'simple-import-sort/exports': 'error'
    }
  }
];
```
The issue I'm facing is with same directory imports not being sorted. Consider the following :
Original State :
```jsx

import {
UploadDocument,
UploadGraphicFile
} from '../../../../api/services/app-announcers/models';
import {
uploadFile,
uploadGraphicFile
} from '../../../../api/services/app-announcers/app-announcers.service';
import useAxiosApiHandler from '../../../../hooks/useAxiosApiHandler';
```

After I run ESLint, it was refactored to :
```jsx
import useAxiosApiHandler from '../../../../hooks/useAxiosApiHandler';
import {
uploadFile,
uploadGraphicFile
} from '../../../../api/services/app-announcers/app-announcers.service';
import {
UploadDocument,
UploadGraphicFile
} from '../../../../api/services/app-announcers/models';
```
As you can see, the imports from `/api` were sorted alphabetically w.r.t their import paths

Now consider another example below :
Original State :
```jsx
import { FC } from 'react';
import Routes from './routes';
import './Overides.scss';
import './App.scss';

const App: FC = () => {
return <Routes />;
};

export default App;
```

After I run ESLint, it was refactored to :
```jsx
import { FC } from 'react';

import './Overides.scss';
import './App.scss';

import Routes from './routes';

const App: FC = () => {
return <Routes />;
};

export default App;
```

As you can see, both the `scss` files are being imported from the same directory, but when I run the ESlint, it does not sort them alphabetically like I expected it to be. I'm not able to understand why.

**Expected :**
I would like to have the scss files being imported from the same directory to be alphabetically ordered, because when it comes to css, the order matters a lot.

---
Raising this issue here as I could not find a dedicated discussion tab for this

**Comment by lydell** [comment]
Hi! `import 'foo';` is considered a side effect import (it is only imported for its side effects, not to provide any values), and the plugin always keeps those in [the original](https://github.com/lydell/eslint-plugin-simple-import-sort?tab=readme-ov-file#is-sorting-importsexports-safe).

**Comment by tejas-1206** [comment]
> Hi! `import 'foo';` is considered a side effect import (it is only imported for its side effects, not to provide any values), and the plugin always keeps those in [the original order for safety](https://github.com/lydell/eslint-plugin-simple-import-sort?tab=readme-ov-file#is-sorting-importsexports-safe).

Ah. So, that means, stylesheet imports are also considered as side effects. Makes sense.
