### ISSUE TITLE
Export default groups

### ISSUE THREAD

**Issue by davidenke** [lydell/eslint-plugin-simple-import-sort#185]
It would be nice to have the import `defaultGroups` exported to customize them.
Just for adding a group all default groups have to be redefined right now.

```json
{
  "rules": {
    "simple-import-sort/imports": [
      "error",
      {
        "groups": [
          ["^\\u0000"],
          ["^node:"],
          ["^@?\\w"],
          ["^"],
          ["^\\."],
          ["\\.css\\?inline"]
        ]
      }
    ]
  }
}
```

It would be easier to do:

```js
import simpleImportSort from 'eslint-plugin-simple-import-sort';

export default [
  {
    plugins: {
      'simple-import-sort': simpleImportSort,
    },
    rules: {
      'simple-import-sort/imports': ['error', {
        groups: [
          ...simpleImportSort.defaultGroups, // spread default groups first
          ['\\.css\\?inline'], // add custom group
        ],
      }],
    },
  },
];
```

Even just adding an `export` to the existing declaration in the `imports.js` would be nice, enabling for something like this:

```js
import { defaultGroups } from 'eslint-plugin-simple-import-sort/imports';
```

**Comment by lydell** [comment]
Hi!

This seems to make it possible to add more groups above or below the default groups. I can see how the code make it clear that you are essentially using the defaults, with just one addition.

However, that’s pretty much all you can do with the defaults. If you want to add a new group in the middle you are out of luck.

Also, while the regex based configuration is very minimal, it is also pretty difficult to get right sometimes. I think it helps when you can see all the regexes in one place, to see how they interact.

So, I don’t want to export the defaults.

In your case, I would recommend using comments to show what parts of the config are copied from the defaults, and what parts are your own.

The defaults change very rarely so it is fine to copy-paste, I think.
