### ISSUE TITLE
Duplicate imports are not optimized

### ISSUE THREAD

**Issue by Zhuvikin** [lydell/eslint-plugin-simple-import-sort#2]
Duplicate imports are to be combined to the one import.

Discovered in release `2.0.0`

**Steps to reproduce:**

Try to fix the following
```
import './styles.scss'
import './styles.scss'
```

**Actual result:**
```
import './styles.scss'
import './styles.scss'
```

**Expected result:**
```
import './styles.scss'
```

**Comment by lydell** [comment]
Merging with #1.
