### ISSUE TITLE
Make a new group for the built-in native node packages

### ISSUE THREAD

**Issue by namnm** [lydell/eslint-plugin-simple-import-sort#20]
For example I want to have those imports into a new separated group:
```js
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import util from 'util';
```
Those packages are node built-in.

**Comment by namnm** [comment]
Thanks for your great work on this plugin anyway!

**Comment by lydell** [comment]
Thanks!

Previous discussion: https://github.com/lydell/eslint-plugin-simple-import-sort/issues/4#issuecomment-459938906

**Comment by bfmiv** [comment]
For anyone who is interested, I have implemented a node builtin group here https://github.com/bfmiv/eslint-plugin-simple-import-sort/tree/nodejs-builtin-group

**Comment by lydell** [comment]
I’ve started thinking about adding an option that lets you customize the grouping. The option would be a function that gets an `import` AST node and returns a number. All imports that get the same number end up in the same group. The groups are sorted numerically. Or something. Just need to figure out what to do about side-effect imports.

**Comment by bfmiv** [comment]
I think the way you're handling side-effect imports now makes perfect sense – always first, no change to order. It's not safe to sort SE imports anyway.

**Comment by lydell** [comment]
I’ve seen people fork this repo to be able to put `import "./styles.scss"` last.

**Comment by bfmiv** [comment]
> I’ve seen people fork this repo to be able to put import "./styles.scss" last.

🤢that's what [css modules](https://github.com/css-modules/css-modules) are for!

**Comment by bfmiv** [comment]
Joking aside - I considered that as well. It would be nice to group by extension, particularly for css / less / sass:

```ts
import 'side-effect';

import React from 'react';

import MyComponent from '../components/MyComponent';

import styles from './styles.scss';
// OR import './styles.scss';
```

**Comment by lydell** [comment]
I’ve come up with an idea that I’d like to experiment with next week.

**Comment by lydell** [comment]
Status update: I’ve made some progress on my idea that will allow customizing this.

**Comment by lydell** [comment]
This is now possible in v5.0.0 using
[custom grouping](https://github.com/lydell/eslint-plugin-simple-import-sort/tree/d1d59be47b08733990a8a62f7caf735cdad420f9#custom-grouping).

For example:

```json
{
  "rules": {
    "simple-import-sort/sort": [
      "error",
      {
        "groups": [
          ["^\\u0000"],
          [
            "^(assert|buffer|child_process|cluster|console|constants|crypto|dgram|dns|domain|events|fs|http|https|module|net|os|path|punycode|querystring|readline|repl|stream|string_decoder|sys|timers|tls|tty|url|util|vm|zlib|freelist|v8|process|async_hooks|http2|perf_hooks)(/.*|$)"
          ],
          ["^@?\\w"],
          ["^[^.]"],
          ["^\\."]
        ]
      }
    ]
  }
}
```

You could also generate this regex if you use a `.js` config. For example:

```js
`^(${require("module").builtinModules.join("|")})(/|$)`;
```

**Comment by bfmiv** [comment]
@lydell this is perfect, thank you!

**Comment by lydell** [comment]
FYI, v8.0.0 now sorts imports starting with `node:` in a separate group, so that’s another way of having a separate group for builtin modules. Adding `node:` prefixes can be autofixed by the [unicorn/prefer-node-protocol](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/33dcaaed54c6cda7110baa9db1e5423097b9a482/docs/rules/prefer-node-protocol.md) rule.
