### ISSUE TITLE
VsCode error

### ISSUE THREAD

**Issue by kivervinicius** [lydell/eslint-plugin-simple-import-sort#23]
> Failed to load plugin 'simple-import-sor' declared in '.eslintrc.js': Cannot find module 'eslint-plugin-simple-import-sor'

`"extends": [
        "eslint:recommended",
        "plugin:react/recommended",
        "plugin:import/errors",
        "plugin:import/warnings",
        "plugin:simple-import-sort"
    ],`

I set to only simple-import-sort but no works

**Comment by kivervinicius** [comment]
sorry i had typed extends

**Comment by el-angel** [comment]
@kivervinicius can you share your config, I have the same issue, but I can't spot what actually solved it
