### ISSUE TITLE
How to remove newline between import groups?

### ISSUE THREAD

**Issue by ymkz** [lydell/eslint-plugin-simple-import-sort#25]
Thanks for nice plugin!

I tried to use this and had one question.
How to remove newline between import groups?
(Or is there no option to remove line breaks?)

```tsx
import fetch from 'cross-fetch'
import { NextPage } from 'next'
import Link from 'next/link'
import React from 'react'

// I want to delete ↑ line...
import { Head } from '~/components/abstracts/head'

```

The config file used is shown below.

<details>
<summary>My ESLint config</summary>
<pre>
<code>
{
  "root": true,
  "env": {
    "es6": true,
    "node": true,
    "browser": true
  },
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaFeatures": { "jsx": true },
    "sourceType": "module"
  },
  "plugins": [
    "react",
    "import",
    "unicorn",
    "security",
    "prettier",
    "react-hooks",
    "simple-import-sort",
    "@typescript-eslint"
  ],
  "extends": [
    "eslint:recommended",
    "plugin:import/errors",
    "plugin:import/warnings",
    "plugin:import/typescript",
    "plugin:react/recommended",
    "plugin:unicorn/recommended",
    "plugin:security/recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:prettier/recommended",
    "prettier/@typescript-eslint",
    "prettier/unicorn",
    "prettier/react"
  ],
  "rules": {
    "prefer-const": "error",
    "react/prop-types": "off",
    "simple-import-sort/sort": "error",
    "react-hooks/rules-of-hooks": "error",
    "react-hooks/exhaustive-deps": "warn",
    "import/newline-after-import": "error",
    "unicorn/prevent-abbreviations": "off",
    "unicorn/consistent-function-scoping": "off",
    "@typescript-eslint/ban-ts-ignore": "off",
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/explicit-member-accessibility": "off",
    "@typescript-eslint/consistent-type-definitions": ["error", "type"]
  },
  "settings": {
    "react": {
      "version": "detect"
    },
    "import/resolver": {
      "babel-module": {}
    },
    "import/parsers": {
      "@typescript-eslint/parser": [".ts", ".tsx"]
    }
  }
}
</code>
</pre>
</details>

**Comment by lydell** [comment]
Hi!

This plugin has no options by design. There is currently no way of removing that newline.

Would you like to tell me more about this unwanted line break? Do you want no linebreaks at all between imports? Or just between those two groups that you showed? Why is it important? Etc.

**Comment by ymkz** [comment]
Thanks for the reply. OK, I undetstand plugin design.

I want to remove line breaks between all import statements. This is my personal opinion because I usually don't put a newline between import statements. So, not important. But I would be happy if option was provided like https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md#newlines-between-ignorealwaysalways-and-inside-groupsnever. 

Thank you for your polite response!

**Comment by hrougier** [comment]
Hi,

Having this option would be nice for people using typescript.

Migrating from tslint to eslint, this plugin is the only one that can behave like tslint [ordered-imports](https://palantir.github.io/tslint/rules/ordered-imports/) rule... except that tslint default rule configuration disables new line between groups.

Would be great to be able to have the same configuration as tslint.

**Comment by lydell** [comment]
@hrougier https://palantir.github.io/tslint/rules/ordered-imports/

> Groups of imports are delineated by blank lines.

But you say the default is having _no_ blank lines between groups?

**Comment by hrougier** [comment]
> But you say the default is having _no_ blank lines between groups?

That's it, blank lines between groups is an option which is not enabled by default:

```json
"rules": {
    "ordered-imports": true // rules acticated, no blank lines
  }
```

```json
"rules": {
    "ordered-imports": [true, { "grouped-imports": true }] // to enable blank lines
  }
```

**Comment by lydell** [comment]
Ok. I guess their docs is a little misleading, then. I have an idea for this that I want to play with this week.

**Comment by lydell** [comment]
I have a thing coming up that will allow customizing this.

**Comment by lydell** [comment]
This is now possible in v5.0.0 using
[custom grouping](https://github.com/lydell/eslint-plugin-simple-import-sort/tree/d1d59be47b08733990a8a62f7caf735cdad420f9#custom-grouping).

For example:

```json
{
  "rules": {
    "simple-import-sort/sort": [
      "error",
      {
        "groups": [["^\\u0000", "^@?\\w", "^[^.]", "^\\."]]
      }
    ]
  }
}
```

**Comment by santomegonzalo** [comment]
This feature of grouping is great but will be nice to make an example on the documentation because it was clear only after searching `newline`

**Comment by keemor** [comment]
Hi @santomegonzalo, @lydell :)
How to remove empty lines between groups? My .eslint looks like this:

```
{
  "plugins": ["simple-import-sort"],
  "extends": "react-app",
  "rules": {
    "simple-import-sort/sort": [
      "warn",
      {
        "groups": [
          // Packages. `react` related packages come first.
          ["^react", "^@?\\w"],
          // Internal packages.
          ["^(components|modules|utils)(/.*|$)"],
          // Side effect imports.
          ["^\\u0000"],
          // Parent imports. Put `..` last.
          ["^\\.\\.(?!/?$)", "^\\.\\./?$"],
          // Other relative imports. Put same-folder imports and `.` last.
          ["^\\./(?=.*/)(?!/?$)", "^\\.(?!/?$)", "^\\./?$"],
          // Style imports.
          ["^.+\\.s?css$"]
        ]
      }
    ],
    "import/first": "warn",
    "import/newline-after-import": "warn",
    "import/no-duplicates": "warn",
  }
}
```

**Comment by lydell** [comment]
@keemor Hi!

You need to put everything in the same array, like this:

```json
{
  "plugins": ["simple-import-sort"],
  "extends": "react-app",
  "rules": {
    "simple-import-sort/sort": [
      "warn",
      {
        "groups": [
          [
            // Packages. `react` related packages come first.
            "^react",
            "^@?\\w",
            // Internal packages.
            "^(components|modules|utils)(/.*|$)",
            // Side effect imports.
            "^\\u0000",
            // Parent imports. Put `..` last.
            "^\\.\\.(?!/?$)", "^\\.\\./?$",
            // Other relative imports. Put same-folder imports and `.` last.
            "^\\./(?=.*/)(?!/?$)", "^\\.(?!/?$)", "^\\./?$",
            // Style imports.
            "^.+\\.s?css$"
          ]
        ]
      }
    ],
    "import/first": "warn",
    "import/newline-after-import": "warn",
    "import/no-duplicates": "warn",
  }
}
```

(I didn’t test that before posting, so forgive me if I made a mistake 🙏)

**Comment by huzaifa-99** [comment]
> This is now possible in v5.0.0 using [custom grouping](https://github.com/lydell/eslint-plugin-simple-import-sort/tree/d1d59be47b08733990a8a62f7caf735cdad420f9#custom-grouping).
> 
> For example:
> 
> ```json
> {
>   "rules": {
>     "simple-import-sort/sort": [
>       "error",
>       {
>         "groups": [["^\\u0000", "^@?\\w", "^[^.]", "^\\."]]
>       }
>     ]
>   }
> }
> ```

Just to expand on this.

For future visitors,  "simple-import-sort/sort" will give error (for v7.0.0)
* `Definition for rule 'simple-import-sort/sort' was not found.eslint(simple-import-sort/sort)` 

Replace the "simple-import-sort/sort" with "simple-import-sort/imports", like this
```
"simple-import-sort/imports": [
      "error",
      {
        "groups": [["^\\u0000", "^@?\\w", "^[^.]", "^\\."]]
      }
]
```

It's also mentioned in the readme [here](https://github.com/lydell/eslint-plugin-simple-import-sort#usage).

Thanks.
