### ISSUE TITLE
Running this rule has suddenly cause broken code to generate

### ISSUE THREAD

**Issue by maraisr** [lydell/eslint-plugin-simple-import-sort#27]
```ts
import { format, parseISO } from 'date-fns';
import React from 'react';
import { createFragmentContainer, graphql } from 'react-relay';
import { FaqAuthor_author } from '~/__generated__/FaqAuthor_author.graphql';
import { FaqAuthor_faq } from '~/__generated__/FaqAuthor_faq.graphql';
import { AuthorInfo } from '~/components/AuthorInfo/AuthorInfo';
```

Is our import block when running `'simple-import-sort/sort': 'off',`, and source code.

However, as soon as we go `'simple-import-sort/sort': 'error',`

This produces:

```ts
import { format, parseISO } from 'date-fns';
import React from 'react';
import { createFragmentContainer, graphql } from 'react-relay';






import { FaqAuthor_author } from '~/__generated__/FaqAuthor_author.graph
q
l
'
;

import { FaqAuthor_faq } from '~/__generated__/FaqAuthor_faq.g
ra
ph
ql
';

import { AuthorInfo } from '~/components/AuthorInfo/AuthorInfo';
```

My eslintrc file:
```js
module.exports = {
	extends: ['plugin:@autoguru/react'],
	env: {
		'shared-node-browser': true,
		browser: true,
	},
	parserOptions: {
		tsconfigRootDir: __dirname,
	},
	settings: {
		'import/resolver': {
			typescript: {
				directory: __dirname,
			},
		},
	},
};
```
> and rule config @ https://github.com/autoguru-au/octane/blob/master/packages/eslint-plugin/configs/base/import.js#L7

**Comment by lydell** [comment]
Hi!

Could you make a minimal repo that I can clone, run `npm ci` and `npm test` to reproduce the issue, please! That would save me a lot of time!

I often do these “repro repos” myself when reporting bugs. It’s really nice! Often I find that there was no issue at all, just me making mistakes. Or that I was about to report the issue to the wrong project.

Thanks!

**Comment by lydell** [comment]
Closing due to no response.
