### ISSUE TITLE
Fix position of a side-effect import

### ISSUE THREAD

**Issue by IlyaSemenov** [lydell/eslint-plugin-simple-import-sort#37]
I'd like to be able to fix position of a side-effect import. Here's the use-case:

```ts
// main.ts, entrypoint of a Vue app

import Vue from 'vue'
import VueBlahBlah from 'vue-blah-blah'
import VueBootstrap from 'vue-bootstrap' // imaginary library with CSS

// Import local assets, including local CSS files.
// This should really go **after** global imports, because those
// may have imported some initial CSS, and local assets should
// follow to be able to override the rules.
import './assets'

import '@/store'
import '@/other/local/module'
```

What if eslint-plugin-simple-import-sort supported some kind of magic comment, similar to `// eslint-disable-next-line`? Like: `// simple-import-sort: keep-group`

**Comment by lydell** [comment]
Hi!

So the library won’t let you import something from it without also causing a side effect? Sounds like bad design to me. Wouldn’t it be better to let the user manage the side effect explicitly, like `import 'vue-bootstrap/global'` and `import VueBootstrap from 'vue-bootstrap'`?

Either way, you could always add _two_ imports anyway – one for the side effect and one for the `VueBootstrap` import.

```js
import "vue-bootstrap";
import "./assets";
import "@/store";
import "@/other/local/module";

import Vue from "vue";
import VueBlahBlah from "vue-blah-blah";
import VueBootstrap from "vue-bootstrap";
```

Does that work for you? I’d really like to avoid adding `// simple-import-sort` comments if not needed. I especially won’t added for a _imaginary_ library :)

**Comment by IlyaSemenov** [comment]
Thanks for the advice. Importing it twice makes sense, somehow it didn't occur to me. Indeed, that's a reasonable workaround compared to the complexity of supporting magic comments.

Also, I didn't seem to find the particular library doing that. I remember I once had it in a project of mine, but it eludes me in which one. I'll close the ticket. (If I recall which library it was, I'll comment additionally.)
