### ISSUE TITLE
eslint-disable is ignored

### ISSUE THREAD

**Issue by moonray** [lydell/eslint-plugin-simple-import-sort#38]
I'm not sure if I'm doing it wrong, but sorting happens even inside a eslint-disable / eslint-enable block.
e.g.

```
import React from 'react';
import { ToastContainer } from 'react-toastify';
import { useAccount, useUser } from 'src/state';

import mapboxgl from 'mapbox-gl';

/* eslint-disable */
import '@feathr/components/style/theme/index.css';
import '@feathr/components/style/global/index.css';
import './ReactApp.css';

// Load after theme/index.css.
import { ErrorBoundary } from '@feathr/components';
/* eslint-enable */

import Routes from './Routes';
```

I would expect anything outside the disable/enable block to get sorted, but inside to be left alone.

**Comment by lydell** [comment]
You can only disable sorting for the _entire chunk_ of imports, not just some of them. This is shown in the [ignore example](https://github.com/lydell/eslint-plugin-simple-import-sort/blob/master/examples/ignore.js). I do link to that in the README, but it could probably be more clear.

In your case, I think you need the “import twice” trick from the example I linked:

```js
import "@feathr/components/style/theme/index.css";
import "@feathr/components/style/global/index.css";
import "./ReactApp.css";
import "@feathr/components";

// eslint-disable-next-line import/no-duplicates
import { ErrorBoundary } from "@feathr/components";
import mapboxgl from "mapbox-gl";
import React from "react";
import { ToastContainer } from "react-toastify";
import { useAccount, useUser } from "src/state";

import Routes from "./Routes";
```

Does that work for you?

See also #37 

I guess the docs could be improved around this, and maybe the rule could be smarter as well.

**Comment by lydell** [comment]
Hmm, actually, you don’t even need to import twice. The `@feather/components` import ends up after `theme/index.css` anyway.

```js
import "@feathr/components/style/theme/index.css";
import "@feathr/components/style/global/index.css";
import "./ReactApp.css";

import { ErrorBoundary } from "@feathr/components";
import mapboxgl from "mapbox-gl";
import React from "react";
import { ToastContainer } from "react-toastify";
import { useAccount, useUser } from "src/state";

import Routes from "./Routes";
```

**Comment by lydell** [comment]
Hi! Since `@feather/components` import ends up after `theme/index.css` by default – could you clarify what your issue is?
