### ISSUE TITLE
Treat @/path imports as absolute

### ISSUE THREAD

**Issue by IlyaSemenov** [lydell/eslint-plugin-simple-import-sort#4]
### Problem

In a project created with `vue-cli`, local components are sorted above global packages:

```js
import Error from "@/components/error.vue"
import { Component, Vue } from "vue-property-decorator"
```

which is counter-intuitive, and may possibly suffer from missing side-effects coming from global imports.

The `@` alias comes from here:
https://github.com/vuejs/vue-cli/blob/486a921e9fc782fe4a9b9dd1bdf82066b1522782/packages/%40vue/cli-service/lib/config/base.js#L49

I understand that the sort plugin treats this as a normal package import, and character code of `@` (64) is smaller than of any letter—I agree that the current behaviour is correct as per documentation.

However, using `@` is a wide spread use case (at least in Vue world) for referring to local modules, so this problem **might** have a solution provided by `simple-import-sort` without needing to update all imports.

### Proposal

I think the simplest solution would be to allow to customize prefixes for "absolute imports" group. As I understand, currently an import is considered absolute if and only if it starts with `/`. What if user could add more prefixes? Something like `{ absolutePrefixes: ['/', '@/'] }`.

### Current workaround

For now I've changed `@/absolute/import` to `~/absolute/import` (`~` sorts after all alphanumeric characters so these imports come directly after all package imports). Granted, it even makes more sense, as `~` means *home* in Unix (and also `~` is a suggested default in e.g. [babel-plugin-root-import](https://github.com/entwicklerstube/babel-plugin-root-import#custom-rootpathprefix)).

However, it's breaking wide spread Vue conventions, so a solution in the sorter allowing to use the default alias `@/` would be appreciated.

Also, logically even `~/package` is an *absolute* import and belong to 'absolute imports' group, not a global package with weird name which just coincidentally happens to be sorted alphabetically after all other packages. This will also be useful for putting line breaks between groups.

**Comment by IlyaSemenov** [comment]
Side note: `~` webpack alias doesn't play well with absolute imports in CSS files.

This works (with `@` pointing to client root):

```css
@import "~@/styles/vars"
```

but this doesn't (with `~` pointing to client root):

```css
@import "~~/styles/vars"
```

**Comment by lydell** [comment]
Good points, we should revisit how special characters are handled when sorting.

Just need to remember to treat e.g. `@storybook/react` as an npm package.

**Comment by IlyaSemenov** [comment]
I think it shouldn't be coupled with special characters only. E.g. I have a legacy project which has global aliases `client/` and `server/` and `import foo from 'client/foo'` is an *absolute* import of a project-local module. So it's a matter of setting up 'absolute' imports. Or, if you prefer, a new group (local absolutes?) which comes between 'true' absolute imports and relative imports.

**Comment by lydell** [comment]
Here's an idea: Use https://github.com/npm/validate-npm-package-name to identify npm packages. That module uses https://github.com/juliangruber/builtins so we could just as well depend on that one too and identify builtin Node.js modules. The groups would be:

1. Side effect imports
2. Node.js builtins
3. npm packages
4. everything else
5. relative imports (starts with a `.`)

"everything else" includes `/`, `@/` and `~/` imports.

Then we could add support for `client/` and `server/` and similar aliases in the future when somebody needs it (via configuration like you suggested).

What do you think?

**Comment by IlyaSemenov** [comment]
It won't work. For example, this is a valid import statement:

```js
import { compose } from 'lodash/fp'
```

but it will be disregarded by `validate-npm-package-name`:

```
> require('validate-npm-package-name')('lodash/fp')
{ validForNewPackages: false,
  validForOldPackages: false,
  errors: [ 'name can only contain URL-friendly characters' ] }
```

Then, I personally don't like separating Node.js builtins from npm packages. I treat them as same class citizens and would prefer them to stay in the same group. (My thinking is: why would I care if package like `https` is a built-in or comes from npm? In either case it's a third party library that I use.)

I understand that some people would prefer the opposite and prefer keeping built-ins at top, but if you decide to extract them to a new group please at least allow the option to merge built-ins and non-built-ins.

So personally I like things the way they already are (with the addition of configurable absolute prefixes).

**Comment by lydell** [comment]
It _will_ work. I was thinking about extracting the first part: `lodash` from `lodash/fp` and `@foo/whatever` from `@foo/whatever/bar`.

Regarding separating builtins, I see what you mean. Maybe we’ll keep them in the third party group.

So it looks like my suggestion will work for you after all?

**Comment by IlyaSemenov** [comment]
Yes, I guess so then.

**Comment by lydell** [comment]
Released in v3.0.0.

For the `client/`/`server/` case I’d suggest renaming them to `Client/`/`Server/` or `~/client/`/`~/server/` or whatever to avoid confusion with npm packages, at least for now.

**Comment by zbeyens** [comment]
It became a common practice to put (at least) the `/src` alias for absolute path, and to sort absolute paths just before the relative paths.

VSCode is handling it by setting this in `jsconfig.json`
```json
"compilerOptions": {
    "baseUrl": "./src"
  },
```

The easiest would be to pass a `./src` parameter to the eslint rule, if possible?

**Comment by lydell** [comment]
@zbeyens Hmm, isn’t that already the case?

```js
import fs from "fs";

import config from "/src/config";

import { getUrl } from "./utils";
```

**Comment by zbeyens** [comment]
@lydell with webpack's alias on `/src`, we can use absolute path:

```js
import config from "config";

import fs from "fs";

import { getUrl } from "./utils";
```

**Comment by lydell** [comment]
I see. I’d recommend choosing an alias that does not look like an npm package name. I think that is less confusing as well. Would that work for you?

**Comment by IlyaSemenov** [comment]
@zbeyens it's more complicated than you perhaps thought. Currently, the plugin operates on the source code (AST tree as passed by ESLint) consistently and idempotently. Given the same set of imports, they will be sorted identically every time (and on any computer). In your scenario however, the order of imports will start depending on the content of `./src` folder. 

That means the plugin will need to implement some non-obvious realtime module lookup. Consider your example:

```js
import config from "config"
```

How would the plugin know if `config` is a "global" npm package or "absolute" package (in your terms) residing in `./src`? For example, let's say there's a file `./src/config/index.tsx`. Does it constitute the "absolute" package? In plain node, no. In Typescript, that will depend on `tsconfig` options. Things will get even more complicated when using Webpack with `resolve.extensions`, `directory-named-webpack-plugin`, etc.

---

Also, I think you're misusing your `./src` folder. Let me elaborate. `./src` is where you'd better put packages that you (in your code) treat as independent *globals*.

For example, let's say you develop a React project and you came up with (imaginary) module `react-currency-filter`. You didn't have time to publish it as an npm package but nevertheless you designed it to work independently (no coupling with the main project). *Then* you put it to `./src/react-currency-filter` and import with:

```js
import ReactCurrencyFilter from "react-currency-filter"
```

This naturally goes to "globals" group of imports, it's no different from other similar packages such as `react-format-time` coming from npm. When you find time and actually publish `react-currency-filter` to npm, your imports will not change.

Your main project however better goes under `./src/acme/*`. Config goes to `./src/acme/config`, which is then either aliased as `~/config` or imported as `acme/config` (with `baseUrl`). In first scenario, it will be sorted to "absolute imports" group automatically. Second scenario is more java-style (compare `com.acme.config`), it goes to "globals" but there your project imports stay together anyway as they are grouped alphabetically.

**Comment by lydell** [comment]
@zbeyens Your case is now possible in v5.0.0 using
[custom grouping](https://github.com/lydell/eslint-plugin-simple-import-sort/tree/d1d59be47b08733990a8a62f7caf735cdad420f9#custom-grouping).

For example:

```json
{
  "rules": {
    "simple-import-sort/sort": [
      "error",
      {
        "groups": [["^\\u0000"], ["^@?\\w"], ["^config(/.*|$)"], ["^\\."]]
      }
    ]
  }
}
```

**Comment by zbeyens** [comment]
Thanks. As a workaround I was using: 
```js
  'import/order': [
      'error',
      {
        groups: [
          'builtin',
          'external',
          'internal',
          'parent',
          'sibling',
          'index',
        ],
      },
    ],
```

But I had to save (`eslint --fix`) from once to multiple times to sort all my imports. 

Now with this plugin, one fix is enough 🎉
