### ISSUE TITLE
Add support for adding comments in top of defined groups

### ISSUE THREAD

**Issue by kiroushi** [lydell/eslint-plugin-simple-import-sort#41]
It'd be great if we could set up a flag to enable/disable adding a comment above each defined group (if a custom definition is provided):

```js
  // ...
  'groups': [
    {
      match: '^\\u0000',
      comment: 'side effects',
    },
    {
      match: '^@?\\w',
      comment: 'package imports,
    },
    // ...
  ],
  // ...
```

I can take care of this feature if you see it fit for your package. Thoughts?

**Comment by lydell** [comment]
Hi!

1. Can you show an example of what your proposed configuration would do?
2. Can you tell me more about your use case to help me understand what you are trying to do?

**Comment by kiroushi** [comment]
Hey @lydell, I'd like not only the imports to be grouped, but also to be prepended by a comment (taking the above as an example):

```js
// side effects
import 'some-polyfill'

// package imports
import Vue from 'vue'
import orderBy from 'lodash/orderBy'

// ...
```

**Comment by lydell** [comment]
Is there any particular reason you want those comments? To me, they just look noisy so I’m not convinced yet!

I’m also thinking – the plugin has to add the comments if they’re missing, right? What if you’ve accidentally added a space in `// package imports` – do you end up with a duplicate comment? What if there’s another comment above – where does the `// package imports` comment go? What if `/* package imports */` is already there? Does that count? Do we need config for `/*` vs `//`? What if you change your configuration – then you’d have lots of old comments left behind that you’d have to clean up.

**Comment by kiroushi** [comment]
In my particular case I'd leave the comments to be managed solely by the plugin; as in, if there's a comment present on the group configuration, prepend it to the import group. In any other case, do nothing (and the plugin would take care of clearing up any previous comment found in the imports block —that most of the time tend to be old stuff that needs to be cleaned up while refactoring—).

It's implemented in a similar way in this package: https://github.com/sagiavinash/eslint-plugin-organize-imports

Given that it would be configurable **and optional**, there's no loss on providing the ability to fully automate (separate into blocks, sort, and prepend a comment for the sake of clarity).

**Comment by lydell** [comment]
Is there are reason you’re not using sagiavinash/eslint-plugin-organize-imports?

**Comment by kiroushi** [comment]
> Is there are reason you’re not using sagiavinash/eslint-plugin-organize-imports?

I think your package is much superior in terms of simplicity + compatibility. I don't really see the point in hardcoding the package route while configuring import groups (the RegEx approach is more powerful as well as simple).

This I suggested is the only tiny bit that I miss in the package, tbh (let it _fully_ automate the imports block).

**Comment by lydell** [comment]
Ok, thanks for sharing!

I’ll leave the issue open to see if more people are interested, but to me this sounds like opening a huge can of worms, complicating things for little gain.

The code for this repo is pretty short and stable, so forking would be an alternative.

**Comment by kiroushi** [comment]
Thanks @lydell, will probably fork at some point then. We can retake this issue if you change your mind. Cheers!
