### ISSUE TITLE
Add an option to sort named imports within one import statement

### ISSUE THREAD

**Issue by nicky1038** [lydell/eslint-plugin-simple-import-sort#42]
Now imports of this kind

`
import { b, a } from 'some-package';
`

Are treated as OK and there is no option to highlight and fix them so they will look like

`
import { a, b } from 'some-package';
`

**Comment by lydell** [comment]
Hi!

This plugin does sort:

`import { b, a } from 'some-package';`

...into:

`import { a, b } from 'some-package';`

Maybe there’s something wrong with your ESLint config? Or there is some other tool somewhere that conflicts?

**Comment by nicky1038** [comment]
@lydell Thank you for the lightning fast reply! Yes, it actually was my fault, the issue can be removed, I am sorry for the concern.
