### ISSUE TITLE
Spacing issue when fixing unsorted imports

### ISSUE THREAD

**Issue by justinzelinsky** [lydell/eslint-plugin-simple-import-sort#44]
First of all -- great plugin. I'm a huge fan of sorting my imports and I've managed to convince my team to include this plugin in our application.

That being said, I'm running into a weird issue where the spacing isn't right after sorting.

Before fix:

![Screen Shot 2020-05-26 at 1 32 47 PM](https://user-images.githubusercontent.com/235744/82931992-bb33eb80-9f55-11ea-9c6f-f7ec438a6b09.png)

After fix:

![Screen Shot 2020-05-26 at 1 33 03 PM](https://user-images.githubusercontent.com/235744/82932002-bff89f80-9f55-11ea-8991-179ad8d296c6.png)

See how there is no space between `alias` and `oneWay` or between `computed` and `get`?

Is this an issue perhaps with another eslint rule?

Thanks!

**Comment by lydell** [comment]
Hi!

Have you read this? https://github.com/lydell/eslint-plugin-simple-import-sort#the-sorting-autofix-causes-some-odd-whitespace

**Comment by justinzelinsky** [comment]
Ah -- looks like I should RTFM. :) Thanks for the quick response.
