### ISSUE TITLE
groups should 1:1 with eslint-plugin-import groups

### ISSUE THREAD

**Issue by corysimmons** [lydell/eslint-plugin-simple-import-sort#45]
Not sure how yours it supposed to work exactly. I saw a bunch of regex...

https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md#groups-array

**Comment by lydell** [comment]
Hi! Can you elaborate on:

- why groups should 1:1
- what that means more specifically
- what you are trying to achieve

**Comment by corysimmons** [comment]
I basically just want eslint-plugin-import + autofix with this group order:

`["builtin", "external", ["parent", "sibling"], "index"]`

**Comment by lydell** [comment]
What have you tried so far?

**Comment by corysimmons** [comment]
Actually I got it working with just plugin-import. 🤷‍♂️
