### ISSUE TITLE
Merge regular and type imports

### ISSUE THREAD

**Issue by remcohaszing** [lydell/eslint-plugin-simple-import-sort#46]
It’s possible to import types and values in a single file. If so, these can be safely merged.

Input:

```tsx
import type { ReactNode } from 'react';
import React from 'react';

export default function Foo(): ReactNode {
  return <div>Hello</div>
}
```

Expected output:

```tsx
import React, { ReactNode } from 'react';

export default function Foo(): ReactNode {
  return <div>Hello</div>
}
```

---

The only case where this is questionable, is if the type is re-exported.

```tsx
import type { ReactNode } from 'react';
import React from 'react';

export { ReactNode };
```

When the imports are merged, this becomes the following, where some tools can’t determine if `ReactNode` is a type or value.

```tsx
import React, { ReactNode } from 'react';

export { ReactNode };
```

I think this is ok though. When properly written, a type export is used for this instead.

```tsx
import React, { ReactNode } from 'react';

export type { ReactNode };
```

TypeScript doesn’t verify this (yet), but I think this makes it ok for this ESLint plugin to fully ignore that situation.

**Comment by lydell** [comment]
Hi!

I’ve thought about merging imports _with the same `from` string_ before, but came to the conclusion that this plugin should _only sort,_ not merge stuff. Instead, I use [import/no-duplicates](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-duplicates.md) for that case. (I even contributed a partial autofix!)

So I think eslint-plugin-simple-import-sort shouldn’t merge type imports like you suggest either. Maybe you could request this in [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import)?

**Comment by remcohaszing** [comment]
Right, I should have seen that. Sorry, my bad!

**Comment by remcohaszing** [comment]
Actually, there’s already an issue for that. https://github.com/benmosher/eslint-plugin-import/issues/909

**Comment by lydell** [comment]
You might want to comment on that issue, since it seems to be about Flow, not TypeScript.
