### ISSUE TITLE
Set sort order of imports without a specifier (side-effects)?

### ISSUE THREAD

**Issue by alfredsgenkins** [lydell/eslint-plugin-simple-import-sort#54]
**Description**

Consider following import declarations:
```js
import { PROPERTY } from './config'; // later refered as "import A"
import './style'; // later refered as "import B"
```

According to AST, the the import A has specifier, the import B has none. I would like to sort imports without specifier last.

Digging into the code, following function was discovered (so it looks like, my case is considered side-effect):

https://github.com/lydell/eslint-plugin-simple-import-sort/blob/7b29c07dd09813dc451fef828c19ba5261537afb/src/sort.js#L841 

The behaviour described is proven by this comment:

https://github.com/lydell/eslint-plugin-simple-import-sort/blob/7b29c07dd09813dc451fef828c19ba5261537afb/src/sort.js#L782

Verdict: the side-effect comes first. I would like it come last.

I am also suspecting the regex I pass is wrong, if that's the case, please let me know. The configs can be seen in examples bellow.

**Motivation**

The feature is specifically important for stylesheet imports, if imported as CSS - the order matters. So, I would like my imports  in module to come last, this means if I extend a component which also imports style, mine module style will have a priority when resolving.

**What I tried**

Plugin options provided:

```js
{
    "groups": [
        [
            "^\\u0000"
        ], // side effect imports
        [
            "^@?[a-z]"
        ], // anything that starts with @ and lowercase
        [
            "^[^.]"
        ], // anything but a dot
        [
            "^\\."
        ] // starting with dot
    ]
}
``` 

Gives me following output:

```js
import './UrlResolver.style';

import PropTypes from 'prop-types';
import { PureComponent } from 'react';

import { CATEGORY, PRODUCT, UNKNOWN } from './UrlResolver.config';
```

The config as follows:

```js
{
    "groups": [
        [
            "^@?[a-z]"
        ], // anything that starts with @ and lowercase
        [
            "^[^.]"
        ], // anything but a dot
        [
            "^\\."
        ], // starting with dot
        [
            "^\\u0000"
        ], // side effect imports
    ]
}
```

Gives me:

```js
import PropTypes from 'prop-types';
import { PureComponent } from 'react';

import './UrlResolver.style';

import { CATEGORY, PRODUCT, UNKNOWN } from './UrlResolver.config';
```

**Expected result:**

An option to configuration is added, which allows to sort side-effects / importds without specifier last.

```js
import PropTypes from 'prop-types';
import { PureComponent } from 'react';

import { CATEGORY, PRODUCT, UNKNOWN } from './UrlResolver.config';

import './UrlResolver.style';
```

**Comment by lydell** [comment]
Hi! This happens because the default regexes are bad. Reordering them is confusing: https://github.com/lydell/eslint-plugin-simple-import-sort/issues/47

This will be improved in the next version. This config should do the trick:

```json
{
    "groups": [
        [
            "^@?[a-z]"
        ], // anything that starts with @ and lowercase
        [
            "^[^.\\u0000]"
        ], // anything but a dot and side effect imports
        [
            "^\\."
        ], // starting with dot
        [
            "^\\u0000"
        ], // side effect imports
    ]
}
```

Let me know if it works for you!

**Comment by alfredsgenkins** [comment]
Works like a charm! Thanks for quick response ❤️
