### ISSUE TITLE
v6.0.0 error  Definition for rule 'simple-import-sort/sort' was not found

### ISSUE THREAD

**Issue by anthony-telljohann** [lydell/eslint-plugin-simple-import-sort#57]
Since upgrading to v6.0.0, when linting, I get the following error:
```txt
error  Definition for rule 'simple-import-sort/sort' was not found  simple-import-sort/sort
```

**Comment by lydell** [comment]
Did you read the changelog? https://github.com/lydell/eslint-plugin-simple-import-sort/blob/main/CHANGELOG.md#version-600-2020-11-15

**Comment by anthony-telljohann** [comment]
I did not! I looked for it in releases but I missed the `CHANGELOG.md`. Thanks @lydell!
