### ISSUE TITLE
Custom groups not working with Prettier (format on save)

### ISSUE THREAD

**Issue by tomcastro** [lydell/eslint-plugin-simple-import-sort#60]
Hi!

Prettier formats my code just fine when adding the plugin as-is, but it's ignoring the custom groups rule while formatting.

Simple Import Sort rules:
```javascript
rules: {
    "simple-import-sort/imports": [
      "error",
      {
        groups: [
          // Node.js builtins. You could also generate this regex if you use a `.js` config.
          // For example: `^(${require("module").builtinModules.join("|")})(/|$)`
          [
            "^(assert|buffer|child_process|cluster|console|constants|crypto|dgram|dns|domain|events|fs|http|https|module|net|os|path|punycode|querystring|readline|repl|stream|string_decoder|sys|timers|tls|tty|url|util|vm|zlib|freelist|v8|process|async_hooks|http2|perf_hooks)(/.*|$)",
          ],
          // Packages. `react` related packages come first.
          ["^react", "^@?\\w"],
          // Internal packages.
          ["^(@|@company|@ui|@src|components|utils|config|vendored-lib|src)(/.*|$)"],
          // Side effect imports.
          ["^\\u0000"],
          // Parent imports. Put `..` last.
          ["^\\.\\.(?!/?$)", "^\\.\\./?$"],
          // Other relative imports. Put same-folder imports and `.` last.
          ["^\\./(?=.*/)(?!/?$)", "^\\.(?!/?$)", "^\\./?$"],
          // Style imports.
          ["^.+\\.s?css$"]
        ]
      }
    ],
    "simple-import-sort/exports": "error",
    "sort-imports": "off",
    "import/order": "off"
  }
```

Expected:
![image](https://user-images.githubusercontent.com/9694556/100398292-a3d0da80-302c-11eb-9eca-e52bb1541a07.png)

Outcome (after saving the file):
![image](https://user-images.githubusercontent.com/9694556/100398307-b814d780-302c-11eb-925c-cb934f0365f0.png)

Formatting works just fine if I run `eslint --fix`, but for some reason, Prettier is not taking this into account and formatting as if I had never written the groups option, even though ESLint clearly sees this as an error.

**Comment by lydell** [comment]
Hi! Can you make a minimal repo that I can clone to reproduce your issue?

**Comment by tomcastro** [comment]
Sure! [Here](https://github.com/tomcastro/simple-import-sort-repro) it is.

Make sure to install everything with yarn, then run `eslint --fix` on any tsx file. Then compare it to running `prettier --write` on the same file. The output should be different and ESLint will complain about running about it.

Let me know if you need anything else :)

**Comment by lydell** [comment]
Thanks for the repro repo!

I don’t really understand what I’m supposed to do though.

This is what I tried:

```
# ESLint finds an error in this file:
~/forks/simple-import-sort-repro main
❯ npx eslint src/App.tsx

/Users/lydell/forks/simple-import-sort-repro/src/App.tsx
  1:1  error  Run autofix to sort these imports!  simple-import-sort/imports

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

# Let’s fix it!
~/forks/simple-import-sort-repro main
❯ npx eslint src/App.tsx --fix

# It moved one import:
~/forks/simple-import-sort-repro main *
❯ git --no-pager diff
diff --git a/src/App.tsx b/src/App.tsx
index 2656773..fb647db 100644
--- a/src/App.tsx
+++ b/src/App.tsx
@@ -1,9 +1,9 @@
 import React from 'react'

-import './App.css'
-
 import logo from './logo.svg'

+import './App.css'
+
 const App: React.FC = () => {
   return (
     <div className="App">

# Now let’s run Prettier.
# Note: `src/App.tsx` was printed in grey here, which means that Prettier made no changes to it.
~/forks/simple-import-sort-repro main *
❯ npx prettier --write src/App.tsx
src/App.tsx 166ms

# Let’s run ESLint again to see if everything is still fine.
# No output means no errors were found.
~/forks/simple-import-sort-repro main *
❯ npx eslint src/App.tsx

# Finally, let’s check the diff again.
# The `./App.css` import is still last as expected.
~/forks/simple-import-sort-repro main *
❯ git --no-pager diff
diff --git a/src/App.tsx b/src/App.tsx
index 2656773..fb647db 100644
--- a/src/App.tsx
+++ b/src/App.tsx
@@ -1,9 +1,9 @@
 import React from 'react'

-import './App.css'
-
 import logo from './logo.svg'

+import './App.css'
+
 const App: React.FC = () => {
   return (
     <div className="App">
```

Everything worked as expected for me there? Can you help me with more details?

**Comment by tomcastro** [comment]
Thanks for the help! I'm still running into this issue, although with different repro steps.

Original file, this will throw an error with ESLint.
```javascript
import React from 'react'

import './App.css'

import logo from './logo.svg'

const App: React.FC = () => {
```

Running `npx eslint src/App.tsx`
```bash
❯ npx eslint src/App.tsx
/Users/tomcastro/Code/tomcastro/simple-import-sort/src/App.tsx
  1:1  error  Run autofix to sort these imports!  simple-import-sort/imports

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

This is expected, so now instead of running `eslint --fix`, try running `npx prettier --write src/App.tsx`:
 ```bash
❯ npx prettier --write src/App.tsx
src/App.tsx 164ms
```

Output is grey, Prettier did not change anything. If we run `npx eslint src/App.tsx` again:
```bash
❯ npx eslint src/App.tsx

/Users/tomcastro/Code/tomcastro/simple-import-sort/src/App.tsx
  1:1  error  Run autofix to sort these imports!  simple-import-sort/imports

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

Same output as before! Prettier did not change anything :(. Finally, we run `npx eslint --fix src/App.tsx` again:
```bash
❯ npx eslint --fix src/App.tsx
❯ git --no-pager diff
diff --git a/src/App.tsx b/src/App.tsx
index 2656773..fb647db 100644
--- a/src/App.tsx
+++ b/src/App.tsx
@@ -1,9 +1,9 @@
 import React from 'react'
 
-import './App.css'
-
 import logo from './logo.svg'
 
+import './App.css'
+
 const App: React.FC = () => {
   return (
     <div className="App">
```

ESLint worked as expected and did change everything according to the rules set on `.eslintrc.json`.

Let me know if these steps work for you or if there's anything else you need!

**Comment by lydell** [comment]
> Same output as before! Prettier did not change anything :(

I don’t understand this. Why do you expect Prettier to have changed anything at this step?

**Comment by lydell** [comment]
I had another look at this today. I discovered that you have [eslint-<strong>plugin</strong>-prettier](https://github.com/prettier/eslint-plugin-prettier) in package.json, but never enable that plugin and its `"prettier/prettier"` rule in .eslintrc.js.

**Comment by lydell** [comment]
@tomcastro Hi! Any updates?

**Comment by lydell** [comment]
Closing due to no response. Feel free to add a comment at any time and we’ll reopen!

**Comment by zhu0629** [comment]
i have same problem
