### ISSUE TITLE
Case-sensitive support

### ISSUE THREAD

**Issue by milesj** [lydell/eslint-plugin-simple-import-sort#64]
Would be nice if specifiers and imports are sorted with case-sensitivity in mind (uppercase after lowercase).

If you could point me to the code where this happens, I can probably contribute it.

**Comment by lydell** [comment]
Hi! Make sure to read through the issue that made this plugin case sensitive first: https://github.com/lydell/eslint-plugin-simple-import-sort/issues/7

**Comment by milesj** [comment]
That's a bit unfortunate, but I can live with it. Thanks for the context and the great plugin.
