### ISSUE TITLE
Definition for rule 'simple-import-sort/sort' was not found.eslint(simple-import-sort/sort)

### ISSUE THREAD

**Issue by lgoldfish** [lydell/eslint-plugin-simple-import-sort#67]
Definition for rule 'simple-import-sort/sort' was not found.eslint(simple-import-sort/sort)

**Comment by lydell** [comment]
https://github.com/lydell/eslint-plugin-simple-import-sort/blob/main/CHANGELOG.md#version-600-2020-11-15
