### ISSUE TITLE
Imports from the same modules should be merged

### ISSUE THREAD

**Issue by IT-CASADO** [lydell/eslint-plugin-simple-import-sort#68]
Can we do this with this rule?

Given input:
```
import { FormControl, FormGroup } from '@angular/forms';
import { Validators } from '@angular/forms';
```

Should be fixed as this:
```
import { FormControl, FormGroup, Validators } from '@angular/forms';
```

This is the same result as with "Organize Imports" from TypeScript/VS Code.
Beside of this, this auto-fixable rule is the best I know!

**Comment by lydell** [comment]
Hi!

As mentioned in the readme, use [import/no-duplicates](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-duplicates.md) merges import statements of the same file. (autofixable, mostly)

See also #1

**Comment by IT-CASADO** [comment]
Thanks for your quick reply. Your suggested no-duplicate rule is working fine for me.

PS: On the other side it would be nice to have (and use) only one rule for imports.
