### ISSUE TITLE
Custom grouping but WITH newlines between groups?

### ISSUE THREAD

**Issue by chalda** [lydell/eslint-plugin-simple-import-sort#70]
Sorry may be I missed this in the docs, but after applying the custom config from https://github.com/lydell/eslint-plugin-simple-import-sort/issues/25#issuecomment-625397779 (which is exactly the kind of grouping i want), it also removed newlines between groups. Is it possible to have both?

**Comment by lydell** [comment]
Hi! This should do the trick:

```js
{
  "plugins": ["simple-import-sort"],
  "extends": "react-app",
  "rules": {
    "simple-import-sort/sort": [
      "warn",
      {
        "groups": [
          // Packages. `react` related packages come first.
          ["^react", "^@?\\w"],
          // Internal packages.
          ["^(components|modules|utils)(/.*|$)"],
          // Side effect imports.
          [^\\u0000"],
          // Parent imports. Put `..` last.
          ["^\\.\\.(?!/?$)", "^\\.\\./?$"],
          // Other relative imports. Put same-folder imports and `.` last.
          ["^\\./(?=.*/)(?!/?$)", "^\\.(?!/?$)", "^\\./?$"],
          // Style imports.
          ["^.+\\.s?css$"]
        ]
      }
    ],
    "import/first": "warn",
    "import/newline-after-import": "warn",
    "import/no-duplicates": "warn",
  }
}
```

> The inner arrays are joined with one newline; the outer arrays are joined with two (creating a blank line).

**Comment by chalda** [comment]
i tried that and was getting an error saying that the values inside groups need to be strings 🤔

**Comment by apeltz** [comment]
@chalda is it possible that you accidentally wrapped each of the groups in an array without removing the original array that they were part of? e.g. your config accidentally looks like this:
```
{
  "groups": [
    [ // EXTRA NESTING
      // Packages. `react` related packages come first.
      ["^react", "^@?\\w"],
      ...other
    ]
  }
```
instead of like this:
```
{
  "groups": [
      // Packages. `react` related packages come first.
      ["^react", "^@?\\w"],
      ...other
  }
```
?

**Comment by lydell** [comment]
Closing because no response.

**Comment by ullalaaron** [comment]
The following setup works correctly (nesting groups)
 "simple-import-sort/imports": [
          "error",
          {
            "groups": [
              // Angular modules
              [
                "^@angular.*"
              ],
              // Node modules (everything that does not start with src or .)
              [
                "^(?![src|.]).*$"
              ],
              // Files inside other folders
              [
                "^src.*"
              ],
              // Files in current folder
              [
                "^[.].*"
              ]
            ]
          }
        ]
