### ISSUE TITLE
Newline between grouped imports

### ISSUE THREAD

**Issue by jimmy-e** [lydell/eslint-plugin-simple-import-sort#77]
I want my imports to not have any new lines between them. I followed the instructions [here](https://github.com/lydell/eslint-plugin-simple-import-sort/issues/25#issuecomment-625397779) and am using the following rules:

.eslintrc.js:
```javascript
module.exports = {
  ...
  rules: {
    ...
    'import/first': 'error',
    'import/newline-after-import': 'error',
    'simple-import-sort/imports': [
      'error',
      {
        groups: [
          [
            "^react",
            "^@?\\w",
            "^(main|core|arc-storybook|viz|design-system|placement|reporting|onboarding)(/.*|$)",
            "^\\u0000",
            "^\\.\\.(?!/?$)",
            "^\\.\\./?$",
            "^.+\\.s?css$",
          ],
        ],
      }
    ],
  },
};
```

I have a sample component, as seen here:

```js
import React from 'react';
import { EuiButton } from '@elastic/eui/src/components/button/button';
import x from './bar';

const Foo: React.FC = () => <EuiButton>Click Me</EuiButton>;

export default Foo;
```

but when I run `prettier-eslint --write src/Foo.tsx`, it adds a space between the second and third import:

```js
import React from 'react';
import { EuiButton } from '@elastic/eui/src/components/button/button';

import x from './bar';

const Foo: React.FC = () => <EuiButton>Click Me</EuiButton>;

export default Foo;
```

How can I make sure that a new line is not added between the second and third import statement? Thanks!

**Comment by lydell** [comment]
Hi! Your config of this plugin looks correct. Can you make a small repo that I can clone to reproduce your problem? I always try to do this myself when reporting issues, and many times I find the problem myself while doing so.

**Comment by jimmy-e** [comment]
Thanks @lydell! Please see [this repo](https://github.com/jimmy-e/simple-import-debug). As always:

1. Run `yarn`
2. Run `eslint --write src/Foo.tsx`
3. Notice that a newline has been added between the second and third import.

I'm assuming there is a conflicting eslint rule, but I'm not sure which?

**Comment by lydell** [comment]
Awesome! The next thing you can do is to enable _only_ the simple-import-sort rules and see if it still happens. If not, reduce the config bit by bit until you find the magic combination that breaks stuff.

**Comment by jimmy-e** [comment]
Apologies @lydell , I should have done that first. I have reduced the eslint to as simple a config as possible but am still getting the same issue; maybe it is an issue with TypeScript. I will try duplicating the repo but without TypeScript and look into this further and will get back to you in a day or so.

**Comment by jimmy-e** [comment]
Hey @lydell , you can see the new repository [here](https://github.com/jimmy-e/simple-import-debug-v2). This has TypeScript removed but still has the same problem. The eslint is the following:

**.eslintrc.js:**
```js
module.exports = {
  plugins: ['simple-import-sort'],
  extends: 'airbnb',
  rules: {
    'simple-import-sort/imports': [
      'error',
      {
        groups: [
          [
            "^react",
            "^@?\\w",
            "^(main|core|arc-storybook|viz|design-system|placement|reporting|onboarding)(/.*|$)",
            "^\\u0000",
            "^\\.\\.(?!/?$)",
            "^\\.\\./?$",
            "^.+\\.s?css$",
          ],
        ],
      }
    ],
  },
};
```

**Comment by lydell** [comment]
Great job! Quick question – does it happen if you remove `extends: 'airbnb'`? If not, you can run `eslint --print-config some/file.js` to “expand” the config, paste that into your .eslintrc and then keep pruning

**Comment by lydell** [comment]
Thank you so much for reducing the example, that is super helpful!

Turns out there was something wrong with your configuration after all. None of your regexes match `./bar`. The documentation says:

> Imports that don’t match any regex are grouped together last.

So that’s what’s happening.

**Comment by jimmy-e** [comment]
Ok great, thanks for the help!

**Comment by Minori-ty** [comment]
> Ok great, thanks for the help!
> 
> Fixed eslint:
> 
> module.exports = {
>   parser: 'babel-eslint',
>   plugins: ['simple-import-sort'],
>   rules: {
>     'simple-import-sort/imports': [
>       'error',
>       {
>         groups: [
>           [
>             "^react",
>             "^@?\\w",
>             "^(main|core|arc-storybook|viz|design-system|placement|reporting|onboarding)(/.*|$)",
>             "^\\u0000",
>             "^\\.\\.(?!/?$)", "^\\.\\./?$",
>             "^\\./(?=.*/)(?!/?$)", "^\\.(?!/?$)", "^\\./?$",
>             "^.+\\.s?css$",
>           ],
>         ],
>       }
>     ],
>   },
> };

It works！Thank you！
