### ISSUE TITLE
Option to ignore filename or pattern

### ISSUE THREAD

**Issue by aMarCruz** [lydell/eslint-plugin-simple-import-sort#8]
@lydell hi, this is a great plugin!
...but I missing an option to ignore some files.
I always put typings (TypeScript) in a separate block:

```typescript
import React from 'react'
import { Button } from './Button'

// typings
import { MyType } from '../types'
```

But with this plugin (and others) there's no way to preserve the order. Even with `/* eslint-disable-next-line */` in some cases.

Any plans for such option?

**Comment by lydell** [comment]
No.

**Comment by aMarCruz** [comment]
@lydell thanks
