### ISSUE TITLE
Alphabetical sorting on capitalized imports

### ISSUE THREAD

**Issue by panosl** [lydell/eslint-plugin-simple-import-sort#80]
I am typing:
```
import { getAppStateForBLE, setBLEBgIsRunning, setBatteryStatus, setBatteryStatusUpdated  } from './NebulizerStorage'
```

And it fixes the sorting to:
```
import { getAppStateForBLE, setBatteryStatus, setBatteryStatusUpdated, setBLEBgIsRunning } from './NebulizerStorage'
```

Shouldn't capitalized names take precedence? ie: `setAB` should come before `setAa`

**Comment by lydell** [comment]
Hi!

The sorting is case insensitive by design. See these issues:

- https://github.com/lydell/eslint-plugin-simple-import-sort/issues/7
- https://github.com/lydell/eslint-plugin-simple-import-sort/issues/64

This is not going to change, but thanks for the nicely written issue!
