### ISSUE TITLE
Fine sorting in a group

### ISSUE THREAD

**Issue by SrBrahma** [lydell/eslint-plugin-simple-import-sort#83]
Hey, nice package! Started using it yesterday.

Here is my desire: I want the 'react' imports on top of the file (but after side effects import group), and after it, the 'react-native' import, as they are related. Then, can happen the alphabetically ordering.

I reaaaally want this, as I always had this pattern and I like it.

Is there any way to do it?

Thanks!

**Comment by lydell** [comment]
Hi! Yes, this should be possible. This example should nudge you in the right direction: https://github.com/lydell/eslint-plugin-simple-import-sort/blob/1f753fb3e5b8eadf6cf9fdda8790d01dd9eade26/examples/.eslintrc.js#L68-L96

For details, see the docs on [Custom Grouping](https://github.com/lydell/eslint-plugin-simple-import-sort#custom-grouping)

Let me know if you need more help, or if you figure it out!

**Comment by SrBrahma** [comment]
Ooooh. I see! Just define the custom group and have react as the first item in the corresponding array, right?

Will try it soon and give you my feedback.

Thanks for the quick answer! :)

**Comment by SrBrahma** [comment]
Took me a while to find out the

https://github.com/lydell/eslint-plugin-simple-import-sort/blob/1f753fb3e5b8eadf6cf9fdda8790d01dd9eade26/examples/.eslintrc.js#L16

but I got it working! I achieved exactly what I really wanted for so long! Be sure that my feelings are filled with gratitude hehe!

As I understood, to have no newlines between the imports (as I don't care about the newlines), there may be just a single group, or, I would need to instal the eslint-plugin-import, that I don't really want it because it has 350 issues and I don't want bugs to deal with.

This is my config:
```json5
"simple-import-sort/imports": ["warn", { groups: [[
  "^\\u0000", // Side effect imports.
  "^react", // `react` related packages come first.
  // Node.js builtins.
  "^(assert|buffer|child_process|cluster|console|constants|crypto|dgram|dns|domain|events|fs|http|https|module|net|os|path|punycode|querystring|readline|repl|stream|string_decoder|sys|timers|tls|tty|url|util|vm|zlib|freelist|v8|process|async_hooks|http2|perf_hooks)(/.*|$)",
  "^@?\\w",
  "^\\.\\.(?!/?$)", "^\\.\\./?$", // Parent imports. Put `..` last.
  "^\\./(?=.*/)(?!/?$)", "^\\.(?!/?$)", "^\\./?$", // Other relative imports. Put same-folder imports and `.` last.
  "^.+\\.s?css$", // Style imports.
]]}],
"simple-import-sort/exports": "warn",
```

and this is my beautiful result, exactly how I like: (:smile:)

```ts
import 'aaa';
import {} from 'react';
import {} from 'react-native';
import {} from 'fs';
import {} from 'abc';
import {} from '../aa';
import {} from './aa';
```

Many many thanks for your work and attention!

**Comment by lydell** [comment]
> As I understood, to have no newlines between the imports (as I don't care about the newlines), there may be just a single group

That is correct!

Thanks for all the kind words!
