### ISSUE TITLE
Add tests for TypeScript 4.5 “type modifiers on import names”

### ISSUE THREAD

**Issue by lydell** [lydell/eslint-plugin-simple-import-sort#89]
https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#type-on-import-names
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#type-modifiers-on-import-names

I think they might already be supported thanks to the syntax already being in use by Flow, but there might be some differences, and we need tests.

**Comment by danielweck** [comment]
Ah, this is a timely "head up", as I am migrating this:

```typescript
import type { T } from 'package';
import { Other } from 'package'; // eslint-disable-line no-duplicate-imports
```

...to this:


```typescript
import { type _, Other } from 'package';
```

(note the removal of `// eslint-disable-line no-duplicate-imports`)

One one hand, I prefer the clear separation of `import type { T } from 'package'` from `import { Other } from 'package'` (I used to have them all bundled together and ordered at the bottom of the entire import "block" at the top of the file) ... but the grouping by `'package'` imports created an interpersed structure so now I might as well embrace TypeScript's 4.5 per-import-name `type` modifier :)

**Comment by lydell** [comment]
@danielweck I don’t quite follow what you’re trying to say. Can you open a new issue if there’s something you need help with or would like to suggest?

**Comment by danielweck** [comment]
Hi, that was merely a message of support for this issue #89 :)
(add tests for this feature)
