### ISSUE TITLE
Support indentation in script tags

### ISSUE THREAD

**Issue by Djaler** [lydell/eslint-plugin-simple-import-sort#9]
I have <script> block in my vue component. For example:
```
<script lang="ts">
    import { Component, Vue, Watch } from 'vue-property-decorator';
    import { Location } from 'vue-router';

    ...
</script>
```
Indent is set to 4 spaces inside script block. 
But when I run linter, I got this error:
![image](https://user-images.githubusercontent.com/7964583/53876449-da282400-4017-11e9-8bd4-a7fd660d4d5f.png)
As you can see, imports are sorted. And if I remove indentation, the error is gone.

**Comment by lydell** [comment]
Ah, script tags. Didn't think about those. This plugin takes a shortcut by enforcing all imports to be at the very start of each line. It does currently not support indentation.

**Comment by lydell** [comment]
Please try v3.1.0 – it should support Vue `<script>` tags.
