### ISSUE TITLE
Support import assertions

### ISSUE THREAD

**Issue by lydell** [lydell/eslint-plugin-simple-import-sort#90]
https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#import-assertions

TypeScript 4.5 supports import assertions, so it’s time to add support for them in this plugin too.

**Comment by danielweck** [comment]
Hello @lydell just a quick message of appreciation for your work, and I hope you will find time to maintain your implementation and stay in sync with the latest TypeScript features (including import assertions).

I have just recently discovered `eslint-plugin-simple-import-sort` which I am now using alongside `eslint-plugin-import` with `eslint-import-resolver-typescript` (my project is hybrid Javascript / Typescript ... your ESLINT import plugin works fine :)

Cheers!
