### ISSUE TITLE
How to autofix on save?

### ISSUE THREAD

**Issue by david-vendel** [lydell/eslint-plugin-simple-import-sort#92]
Hello, I use VSCode, Prettier and Eslint. 
What do I need to cofigure to run this simple sort automatically on format? (On save). Is it even possible?
Thank you!

**Comment by lydell** [comment]
I have this in my VSCode settings.json:

```
    "editor.codeActionsOnSave": {
        "source.fixAll.eslint": true
    }
```

It’s surprisingly hard to find that in vscode-eslint’s readme! https://github.com/microsoft/vscode-eslint/ 🤯

**Comment by justdvl** [comment]
Thank you very much @lydell , works perfectly and indeed I see it there as well now :)
