### ISSUE TITLE
Share example repo which uses this plugin with prettier

### ISSUE THREAD

**Issue by rajjaiswalsaumya** [lydell/eslint-plugin-simple-import-sort#95]
Can you please share an example project which can be used to copy the configs ?

**Comment by lydell** [comment]
Hi! There’s no point in such an example really. [Set up Prettier](https://prettier.io/docs/en/install.html) (pay extra attention to the [ESLint section](https://prettier.io/docs/en/install.html#eslint-and-other-linters) if you want to use ESLint for more than import sorting) and separately [set up eslint-plugin-simple-import-sort](https://github.com/lydell/eslint-plugin-simple-import-sort#installation). Prettier and eslint-plugin-simple-import-sort are completely separate tools. Their only connection is that I’ve made sure that they place nice together and don’t cause conflicts.
