### ISSUE TITLE
Enforce object-curly-newline without using prettier

### ISSUE THREAD

**Issue by NicholasAsimov** [lydell/eslint-plugin-simple-import-sort#97]
Hi! Couldn't find a similar issue for this plugin.

Is it possible to enforce long import statements to be strictly multiline, basically following this rule: https://github.com/airbnb/javascript#modules--multiline-imports-over-newlines.

Can't seem to make ESLint autofix like this when only this plugin is used for imports.

Long imports autofix to this:

```js
import {
  Box, Container, Flex, Icon, IconButton, LinkOverlay,
  LinkOverlayProps, ListIcon, ListItemProps, MenuIcon, SimpleGrid, SimpleGridProps, StackItem,
} from '@chakra-ui/react';
```

I'm trying to achieve this:
```js
import {
  Box,
  Container,
  Flex,
  Icon,
  IconButton,
  LinkOverlay,
  LinkOverlayProps,
  ListIcon,
  ListItemProps,
  MenuIcon,
  SimpleGrid,
  SimpleGridProps,
  StackItem,
} from '@chakra-ui/react';
```

My eslint config:

```js
module.exports = {
  env: {
    browser: true,
    es2021: true,
  },
  extends: [
    'airbnb',
    'airbnb/hooks',
    'airbnb-typescript',
    'plugin:react/jsx-runtime',
    'plugin:@typescript-eslint/recommended',
  ],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 'latest',
    sourceType: 'module',
    project: './tsconfig.json',
  },
  plugins: [
    'react',
    '@typescript-eslint',
    'simple-import-sort',
  ],
  rules: {
    'react/jsx-filename-extension': 'off',
    'react/jsx-one-expression-per-line': 'off',

    'sort-imports': 'off',
    'import/order': 'off',
    'simple-import-sort/imports': 'error',
  },
};

```

**Comment by lydell** [comment]
Hi! This plugin tries to _only_ sort your imports, leaving formatting up to you or other ESLint rules or Prettier.

Have you tried using `object-curly-newline` as the Airbnb docs suggest?

**Comment by NicholasAsimov** [comment]
Yeah you're definitely right, for some reason I thought that it will conflict with this plugin even though it's a separate thing.

But for anyone looking to do this with eslint only it looks like `object-curly-newline` can't enforce each import to be on a separate line, so a plugin like https://github.com/ruudandriessen/eslint-plugin-modules-newline is needed to get this behavior without prettier.

This is definitely outside of this package's scope, closing.
