### ISSUE TITLE
blankline after last import

### ISSUE THREAD

**Issue by undefinederror** [lydell/eslint-plugin-simple-import-sort#99]
Is it possible to force a blackline after the last import? 

this
```js
import {x} from './x.ts'
import {y} from './y.ts'
interface Foo {
}
```
into this?
```js
import {x} from './x.ts'
import {y} from './y.ts'

interface Foo {
}
```

**Comment by lydell** [comment]
Hi! You can use https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/newline-after-import.md for that, as mentioned in the [example configuration](https://github.com/lydell/eslint-plugin-simple-import-sort#example-configuration).

**Comment by undefinederror** [comment]
thank you!
